-- 014-estab-scian-municipio-backfill.sql — audit #131 + #40 (2026-09-26)
--
-- Brings the loaded rows in line with the fixed src/db/loader.ts transform():
--
--   #131 clase_actividad_id came from CLEE chars 6-11, which keep the class
--        from registration and miss every later reclassification (~12% of
--        CDMX rows; e.g. 'Comercio al por menor en tiendas de abarrotes...'
--        stored as 464111 pharmacy). It is now the Clase_actividad label's
--        code from src/db/scian_clase_catalog.json (929 labels, catalog of
--        2026-09-27); labels not in the catalog keep their CLEE code.
--        sector / subsector / rama / subrama become that code's prefixes.
--   #40  municipio held the LOCALIDAD (first Ubicacion segment). It is now
--        the mixed-case segment(s) before the state, same rule as
--        extractMunicipio() in loader.ts.
--
-- One UPDATE per entidad (autocommit, \gexec), touching only rows whose
-- values change; statement_timeout is lifted for the session. Refuses to run
-- until 014-estab-updated-at-trigger.sql is applied, so the backfill does not
-- stamp updated_at. Idempotent: a second run updates 0 rows.
--
-- The VALUES list below is src/db/scian_clase_catalog.json verbatim; if the
-- catalog is regenerated (scripts/gen-scian-clase-catalog.ts), regenerate
-- this list too.
--
-- Afterwards: ./scripts/refresh-matviews.sh (the sector/rama/clase MVs read
-- these columns). The dead tuples are compacted by a later maintenance step.
--
--   docker exec -i supabase-db psql -U postgres -d postgres -v ON_ERROR_STOP=1 -f - < scripts/migrations/014-estab-scian-municipio-backfill.sql

\set ON_ERROR_STOP on
SET statement_timeout = 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger
     WHERE tgrelid = 'establecimientos'::regclass
       AND tgname = 'trg_estab_updated_at'
       AND pg_get_triggerdef(oid) LIKE '%WHEN%raw_json%'
  ) THEN
    RAISE EXCEPTION 'apply scripts/migrations/014-estab-updated-at-trigger.sql first';
  END IF;
END $$;

CREATE TEMP TABLE scian_clase_catalog (
  label text PRIMARY KEY,
  code  text NOT NULL CHECK (code ~ '^[0-9]{6}$')
);

INSERT INTO scian_clase_catalog (label, code) VALUES
  ('Acabado de productos textiles', '313310'),
  ('Actividades administrativas de instituciones de bienestar social', '931610'),
  ('Actividades de seguridad nacional', '931810'),
  ('Acuñación e impresión de monedas', '339911'),
  ('Administración de aeropuertos y helipuertos', '488112'),
  ('Administración de cajas de pensión y de seguros independientes', '524220'),
  ('Administración de cementerios pertenecientes al sector privado', '812321'),
  ('Administración de cementerios pertenecientes al sector público', '812320'),
  ('Administración de puertos y muelles', '488310'),
  ('Administración pública en general', '931210'),
  ('Agencias de anuncios publicitarios', '541850'),
  ('Agencias de cobranza', '561440'),
  ('Agencias de colocación', '561310'),
  ('Agencias de compra de medios a petición del cliente', '541830'),
  ('Agencias de correo directo', '541860'),
  ('Agencias de empleo temporal', '561320'),
  ('Agencias de publicidad', '541810'),
  ('Agencias de relaciones públicas', '541820'),
  ('Agencias de representación de medios', '541840'),
  ('Agencias de viajes', '561510'),
  ('Agentes y representantes de artistas, deportistas y similares', '711410'),
  ('Agentes, ajustadores y gestores de seguros y fianzas', '524210'),
  ('Agrupaciones de autoayuda para alcohólicos y personas con otras adicciones', '624191'),
  ('Alineación y balanceo de automóviles y camiones', '811116'),
  ('Almacenamiento con refrigeración', '493120'),
  ('Almacenamiento de productos agrícolas que no requieren refrigeración', '493130'),
  ('Almacenes generales de depósito', '493111'),
  ('Alquiler de aparatos eléctricos y electrónicos para el hogar y personales', '532210'),
  ('Alquiler de autobuses con chofer', '485510'),
  ('Alquiler de autobuses, minibuses y remolques sin chofer', '532122'),
  ('Alquiler de automóviles con chofer', '485320'),
  ('Alquiler de automóviles sin chofer', '532110'),
  ('Alquiler de camiones de carga sin chofer', '532121'),
  ('Alquiler de equipo de cómputo y de otras máquinas y mobiliario de oficina', '532420'),
  ('Alquiler de equipo de transporte, excepto terrestre', '532412'),
  ('Alquiler de maquinaria y equipo agropecuario, pesquero y para la industria manufacturera', '532491'),
  ('Alquiler de maquinaria y equipo comercial y de servicios', '532493'),
  ('Alquiler de maquinaria y equipo para construcción, minería y actividades forestales', '532411'),
  ('Alquiler de maquinaria y equipo para mover, levantar y acomodar materiales', '532492'),
  ('Alquiler de mesas, sillas, vajillas y similares', '532282'),
  ('Alquiler de otros artículos para el hogar y personales', '532289'),
  ('Alquiler de prendas de vestir', '532281'),
  ('Alquiler sin intermediación de edificios industriales dentro de un parque industrial', '531116'),
  ('Alquiler sin intermediación de oficinas y locales comerciales', '531114'),
  ('Alquiler sin intermediación de otros bienes raíces', '531119'),
  ('Alquiler sin intermediación de salones para fiestas y convenciones', '531113'),
  ('Alquiler sin intermediación de teatros, estadios, auditorios y similares', '531115'),
  ('Alquiler sin intermediación de viviendas amuebladas', '531111'),
  ('Alquiler sin intermediación de viviendas no amuebladas', '531112'),
  ('Artistas, escritores y técnicos independientes', '711510'),
  ('Aserrado de tablas y tablones', '321112'),
  ('Asesoría en inversiones', '523910'),
  ('Asilos y otras residencias del sector privado para el cuidado de ancianos', '623311'),
  ('Asilos y otras residencias del sector público para el cuidado de ancianos', '623312'),
  ('Asociaciones regulatorias de actividades recreativas', '813140'),
  ('Asociaciones y organizaciones civiles', '813230'),
  ('Asociaciones y organizaciones de profesionistas', '813130'),
  ('Asociaciones y organizaciones laborales y sindicales', '813120'),
  ('Asociaciones y organizaciones religiosas', '813210'),
  ('Asociaciones, organizaciones y cámaras de productores, comerciantes y prestadores de servicios', '813110'),
  ('Autotransporte foráneo con refrigeración', '484233'),
  ('Autotransporte foráneo de madera', '484234'),
  ('Autotransporte foráneo de materiales para la construcción', '484231'),
  ('Autotransporte foráneo de materiales y residuos peligrosos', '484232'),
  ('Autotransporte foráneo de productos agrícolas sin refrigeración', '484121'),
  ('Autotransporte local con refrigeración', '484223'),
  ('Autotransporte local de madera', '484224'),
  ('Autotransporte local de materiales para la construcción', '484221'),
  ('Autotransporte local de materiales y residuos peligrosos', '484222'),
  ('Autotransporte local de productos agrícolas sin refrigeración', '484111'),
  ('Banca de desarrollo', '522210'),
  ('Banca múltiple', '522110'),
  ('Baños públicos', '812120'),
  ('Bares, cantinas y similares', '722412'),
  ('Beneficio de productos agrícolas', '115113'),
  ('Beneficio del arroz', '311211'),
  ('Beneficio del café', '311921'),
  ('Beneficio del tabaco', '312210'),
  ('Bibliotecas y archivos del sector privado', '519211'),
  ('Bibliotecas y archivos del sector público', '519122'),
  ('Billares', '713991'),
  ('Boliches', '713950'),
  ('Bolsa de valores', '523210'),
  ('Bufetes jurídicos', '541110'),
  ('Cabañas, villas y similares', '721190'),
  ('Cafeterías, fuentes de sodas, neverías, refresquerías y similares', '722515'),
  ('Cajas de ahorro popular', '522320'),
  ('Camaronicultura y acuicultura de otros crustáceos en agua salada', '112511'),
  ('Campamentos y albergues recreativos', '721210'),
  ('Campos de golf', '713910'),
  ('Cantantes y grupos musicales del sector privado', '711131'),
  ('Captación, tratamiento y suministro de agua realizados por el sector privado', '221311'),
  ('Captación, tratamiento y suministro de agua realizados por el sector público', '222111'),
  ('Casas de bolsa', '523110'),
  ('Casas de empeño', '522452'),
  ('Casas de juegos electrónicos', '713120'),
  ('Centros cambiarios', '523122'),
  ('Centros de acondicionamiento físico del sector privado', '713943'),
  ('Centros de acondicionamiento físico del sector público', '713944'),
  ('Centros de planificación familiar del sector privado', '621411'),
  ('Centros de planificación familiar del sector público', '621412'),
  ('Centros del sector privado de atención médica externa para enfermos mentales y adictos', '621421'),
  ('Centros del sector privado dedicados a la atención y cuidado diurno de ancianos y discapacitados', '624121'),
  ('Centros del sector público de atención médica externa para enfermos mentales y adictos', '621422'),
  ('Centros del sector público dedicados a la atención y cuidado diurno de ancianos y discapacitados', '624122'),
  ('Centros generales de alquiler', '532310'),
  ('Centros nocturnos, discotecas y similares', '722411'),
  ('Cerrajerías', '811491'),
  ('Clínicas de consultorios médicos del sector privado', '621115'),
  ('Clubes deportivos del sector privado', '713941'),
  ('Clubes o ligas de aficionados', '713992'),
  ('Colocación de muros falsos y aislamiento', '238311'),
  ('Colocación de pisos cerámicos y azulejos', '238340'),
  ('Colocación de pisos flexibles y de madera', '238330'),
  ('Comercio al por mayor de abarrotes', '431110'),
  ('Comercio al por mayor de artículos de joyería y relojes', '433220'),
  ('Comercio al por mayor de artículos de papelería', '433410'),
  ('Comercio al por mayor de artículos de perfumería y cosméticos', '433210'),
  ('Comercio al por mayor de artículos desechables', '434240'),
  ('Comercio al por mayor de artículos y accesorios para diseño y pintura artística', '435312'),
  ('Comercio al por mayor de artículos y aparatos deportivos', '433313'),
  ('Comercio al por mayor de bebidas no alcohólicas y hielo', '431211'),
  ('Comercio al por mayor de blancos', '432112'),
  ('Comercio al por mayor de botanas y frituras', '431192'),
  ('Comercio al por mayor de calzado', '432130'),
  ('Comercio al por mayor de camiones', '436111'),
  ('Comercio al por mayor de carne de aves', '431122'),
  ('Comercio al por mayor de carnes rojas', '431121'),
  ('Comercio al por mayor de cemento, tabique y grava', '434211'),
  ('Comercio al por mayor de cerveza', '431213'),
  ('Comercio al por mayor de cigarros, puros y tabaco', '431220'),
  ('Comercio al por mayor de combustibles de uso industrial', '434230'),
  ('Comercio al por mayor de conservas alimenticias', '431193'),
  ('Comercio al por mayor de cueros y pieles', '432113'),
  ('Comercio al por mayor de desechos de papel y de cartón', '434312'),
  ('Comercio al por mayor de desechos de plástico', '434314'),
  ('Comercio al por mayor de desechos de vidrio', '434313'),
  ('Comercio al por mayor de desechos metálicos', '434311'),
  ('Comercio al por mayor de discos y casetes', '433311'),
  ('Comercio al por mayor de dulces y materias primas para repostería', '431180'),
  ('Comercio al por mayor de electrodomésticos menores y aparatos de línea blanca', '433510'),
  ('Comercio al por mayor de embutidos', '431170'),
  ('Comercio al por mayor de envases en general, papel y cartón para la industria', '434223'),
  ('Comercio al por mayor de equipo de telecomunicaciones, fotografía y cinematografía', '435311'),
  ('Comercio al por mayor de equipo y material eléctrico', '434225'),
  ('Comercio al por mayor de fertilizantes, plaguicidas y semillas para siembra', '434111'),
  ('Comercio al por mayor de fibras, hilos y telas', '432111'),
  ('Comercio al por mayor de frutas y verduras frescas', '431130'),
  ('Comercio al por mayor de ganado y aves en pie', '434228'),
  ('Comercio al por mayor de huevo', '431140'),
  ('Comercio al por mayor de juguetes y bicicletas', '433312'),
  ('Comercio al por mayor de leche y otros productos lácteos', '431160'),
  ('Comercio al por mayor de libros', '433420'),
  ('Comercio al por mayor de madera para la construcción y la industria', '434224'),
  ('Comercio al por mayor de maquinaria y equipo agropecuario, forestal y para la pesca', '435110'),
  ('Comercio al por mayor de maquinaria y equipo para la construcción y la minería', '435210'),
  ('Comercio al por mayor de maquinaria y equipo para la industria manufacturera', '435220'),
  ('Comercio al por mayor de maquinaria y equipo para otros servicios y para actividades comerciales', '435319'),
  ('Comercio al por mayor de materiales metálicos para la construcción y la manufactura', '434221'),
  ('Comercio al por mayor de medicamentos veterinarios y alimentos para animales, excepto mascotas', '434112'),
  ('Comercio al por mayor de miel', '431194'),
  ('Comercio al por mayor de mobiliario y equipo de oficina', '435412'),
  ('Comercio al por mayor de mobiliario, equipo e instrumental médico y de laboratorio', '435313'),
  ('Comercio al por mayor de mobiliario, equipo, y accesorios de cómputo', '435411'),
  ('Comercio al por mayor de otra maquinaria y equipo de uso general', '435419'),
  ('Comercio al por mayor de otras materias primas para otras industrias', '434229'),
  ('Comercio al por mayor de otros alimentos', '431199'),
  ('Comercio al por mayor de otros materiales de desecho', '434319'),
  ('Comercio al por mayor de otros materiales para la construcción, excepto de madera y metálicos', '434219'),
  ('Comercio al por mayor de otros productos textiles', '432119'),
  ('Comercio al por mayor de pan y pasteles', '431191'),
  ('Comercio al por mayor de partes y refacciones nuevas para automóviles, camionetas y camiones', '436112'),
  ('Comercio al por mayor de pescados y mariscos', '431123'),
  ('Comercio al por mayor de pintura', '434226'),
  ('Comercio al por mayor de productos farmacéuticos', '433110'),
  ('Comercio al por mayor de productos químicos para la industria farmacéutica y para otro uso industrial', '434222'),
  ('Comercio al por mayor de revistas y periódicos', '433430'),
  ('Comercio al por mayor de ropa, bisutería y accesorios de vestir', '432120'),
  ('Comercio al por mayor de semillas y granos alimenticios, especias y chiles secos', '431150'),
  ('Comercio al por mayor de vidrios y espejos', '434227'),
  ('Comercio al por mayor de vinos y licores', '431212'),
  ('Comercio al por menor de aceites y grasas lubricantes, aditivos y similares para vehículos de motor', '468420'),
  ('Comercio al por menor de alfombras, cortinas, tapices y similares', '466311'),
  ('Comercio al por menor de antigüedades y obras de arte', '466313'),
  ('Comercio al por menor de artículos de joyería y relojes', '465112'),
  ('Comercio al por menor de artículos de mercería y bonetería', '463113'),
  ('Comercio al por menor de artículos de papelería', '465311'),
  ('Comercio al por menor de artículos de perfumería y cosméticos', '465111'),
  ('Comercio al por menor de artículos desechables', '465914'),
  ('Comercio al por menor de artículos ortopédicos', '464122'),
  ('Comercio al por menor de artículos para albercas y otros artículos', '467117'),
  ('Comercio al por menor de artículos para la limpieza', '467115'),
  ('Comercio al por menor de artículos religiosos', '465913'),
  ('Comercio al por menor de artículos usados', '466410'),
  ('Comercio al por menor de artículos y aparatos deportivos', '465215'),
  ('Comercio al por menor de automóviles y camionetas nuevos', '468111'),
  ('Comercio al por menor de automóviles y camionetas usados', '468112'),
  ('Comercio al por menor de bebidas no alcohólicas y hielo', '461213'),
  ('Comercio al por menor de bicicletas', '465213'),
  ('Comercio al por menor de bisutería y accesorios de vestir', '463215'),
  ('Comercio al por menor de blancos', '463112'),
  ('Comercio al por menor de calzado', '463310'),
  ('Comercio al por menor de carne de aves', '461122'),
  ('Comercio al por menor de carnes rojas', '461121'),
  ('Comercio al por menor de cerveza', '461212'),
  ('Comercio al por menor de cigarros, puros y tabaco', '461220'),
  ('Comercio al por menor de cristalería, loza y utensilios de cocina', '466114'),
  ('Comercio al por menor de discos y casetes', '465211'),
  ('Comercio al por menor de disfraces, vestimenta regional y vestidos de novia', '463214'),
  ('Comercio al por menor de dulces y materias primas para repostería', '461160'),
  ('Comercio al por menor de electrodomésticos menores y aparatos de línea blanca', '466112'),
  ('Comercio al por menor de equipo y material fotográfico', '465214'),
  ('Comercio al por menor de frutas y verduras frescas', '461130'),
  ('Comercio al por menor de gas L. P. en cilindros y para tanques estacionarios', '468412'),
  ('Comercio al por menor de gas L. P. en estaciones de carburación', '468413'),
  ('Comercio al por menor de gasolina y diesel', '468411'),
  ('Comercio al por menor de instrumentos musicales', '465216'),
  ('Comercio al por menor de juguetes', '465212'),
  ('Comercio al por menor de lámparas ornamentales y candiles', '466314'),
  ('Comercio al por menor de leche, otros productos lácteos y embutidos', '461150'),
  ('Comercio al por menor de lencería', '463213'),
  ('Comercio al por menor de lentes', '464121'),
  ('Comercio al por menor de libros', '465312'),
  ('Comercio al por menor de llantas y cámaras para automóviles, camionetas y camiones', '468213'),
  ('Comercio al por menor de mascotas', '465911'),
  ('Comercio al por menor de materiales para la construcción en tiendas de autoservicio especializadas', '467116'),
  ('Comercio al por menor de mobiliario, equipo y accesorios de cómputo', '466211'),
  ('Comercio al por menor de motocicletas', '468311'),
  ('Comercio al por menor de muebles para el hogar', '466111'),
  ('Comercio al por menor de muebles para jardín', '466113'),
  ('Comercio al por menor de otros alimentos', '461190'),
  ('Comercio al por menor de otros artículos de uso personal', '465919'),
  ('Comercio al por menor de otros artículos para la decoración de interiores', '466319'),
  ('Comercio al por menor de otros combustibles', '468419'),
  ('Comercio al por menor de otros vehículos de motor', '468319'),
  ('Comercio al por menor de paletas de hielo y helados', '461170'),
  ('Comercio al por menor de pañales desechables', '463217'),
  ('Comercio al por menor de partes y refacciones nuevas para automóviles, camionetas y camiones', '468211'),
  ('Comercio al por menor de partes y refacciones usadas para automóviles, camionetas y camiones', '468212'),
  ('Comercio al por menor de pescados y mariscos', '461123'),
  ('Comercio al por menor de pintura', '467113'),
  ('Comercio al por menor de pisos y recubrimientos cerámicos', '467112'),
  ('Comercio al por menor de plantas y flores naturales', '466312'),
  ('Comercio al por menor de productos naturistas, medicamentos homeopáticos y de complementos alimenticios', '464113'),
  ('Comercio al por menor de regalos', '465912'),
  ('Comercio al por menor de revistas y periódicos', '465313'),
  ('Comercio al por menor de ropa de bebé', '463212'),
  ('Comercio al por menor de ropa de cuero y piel y de otros artículos de estos materiales', '463216'),
  ('Comercio al por menor de ropa, excepto de bebé y lencería', '463211'),
  ('Comercio al por menor de semillas y granos alimenticios, especias y chiles secos', '461140'),
  ('Comercio al por menor de sombreros', '463218'),
  ('Comercio al por menor de telas', '463111'),
  ('Comercio al por menor de teléfonos y otros aparatos de comunicación', '466212'),
  ('Comercio al por menor de vidrios y espejos', '467114'),
  ('Comercio al por menor de vinos y licores', '461211'),
  ('Comercio al por menor en estaciones de gas natural vehicular', '468414'),
  ('Comercio al por menor en ferreterías y tlapalerías', '467111'),
  ('Comercio al por menor en minisupers', '462112'),
  ('Comercio al por menor en supermercados', '462111'),
  ('Comercio al por menor en tiendas de abarrotes, ultramarinos y misceláneas', '461110'),
  ('Comercio al por menor en tiendas de artesanías', '465915'),
  ('Comercio al por menor en tiendas departamentales', '462210'),
  ('Comercio al por menor exclusivamente a través de Internet, y catálogos impresos, televisión y similares', '469110'),
  ('Compañías afianzadoras', '524130'),
  ('Compañías de autofinanciamiento', '522440'),
  ('Compañías de seguros', '524110'),
  ('Compañías de teatro del sector privado', '711111'),
  ('Complejos siderúrgicos', '331111'),
  ('Confección de cortinas, blancos y similares', '314120'),
  ('Confección de costales', '314911'),
  ('Confección de otros accesorios y prendas de vestir no clasificados en otra parte', '315999'),
  ('Confección de prendas de vestir de cuero, piel y de materiales sucedáneos', '315210'),
  ('Confección de prendas de vestir sobre medida', '315225'),
  ('Confección de productos de textiles recubiertos y de materiales sucedáneos', '314912'),
  ('Confección de sombreros y gorras', '315991'),
  ('Confección en serie de camisas', '315222'),
  ('Confección en serie de disfraces y trajes típicos', '315224'),
  ('Confección en serie de otra ropa exterior de materiales textiles', '315229'),
  ('Confección en serie de ropa interior y de dormir', '315221'),
  ('Confección en serie de uniformes', '315223'),
  ('Confección, bordado y deshilado de productos textiles', '314991'),
  ('Congelación de frutas y verduras', '311411'),
  ('Congelación de guisos y otros alimentos preparados', '311412'),
  ('Conservación de frutas y verduras por procesos distintos a la congelación y la deshidratación', '311422'),
  ('Conservación de guisos y otros alimentos preparados por procesos distintos a la congelación', '311423'),
  ('Construcción de carreteras, puentes y similares', '237312'),
  ('Construcción de obras de generación y conducción de energía eléctrica', '237131'),
  ('Construcción de obras de urbanización', '237212'),
  ('Construcción de obras marítimas, fluviales y subacuáticas', '237992'),
  ('Construcción de obras para el tratamiento, distribución y suministro de agua y drenaje', '237111'),
  ('Construcción de obras para telecomunicaciones', '237132'),
  ('Construcción de obras para transporte eléctrico y ferroviario', '237993'),
  ('Construcción de plantas de refinería y petroquímica', '237122'),
  ('Construcción de presas y represas', '237991'),
  ('Construcción de sistemas de distribución de petróleo y gas', '237121'),
  ('Construcción de sistemas de riego agrícola', '237112'),
  ('Consultorios de medicina especializada del sector privado', '621113'),
  ('Consultorios de medicina general del sector privado', '621111'),
  ('Consultorios de medicina general del sector público', '621112'),
  ('Consultorios de nutriólogos y dietistas del sector privado', '621391'),
  ('Consultorios de nutriólogos y dietistas del sector público', '621392'),
  ('Consultorios de optometría', '621320'),
  ('Consultorios de psicología del sector privado', '621331'),
  ('Consultorios de psicología del sector público', '621332'),
  ('Consultorios de quiropráctica del sector privado', '621311'),
  ('Consultorios de quiropráctica del sector público', '621312'),
  ('Consultorios del sector privado de audiología y de terapia ocupacional, física y del lenguaje', '621341'),
  ('Consultorios del sector público de audiología y de terapia ocupacional, física y del lenguaje', '621342'),
  ('Consultorios dentales del sector privado', '621211'),
  ('Consultorios dentales del sector público', '621212'),
  ('Corporativos', '551111'),
  ('Corte y empacado de carne de ganado, aves y otros animales comestibles', '311612'),
  ('Curtido y acabado de cuero y piel', '316110'),
  ('Departamentos y casas amueblados con servicios de hotelería', '721312'),
  ('Deshidratación de frutas y verduras', '311421'),
  ('Despachos de investigación de solvencia financiera', '561450'),
  ('Despepite de algodón', '115112'),
  ('Diseño de modas y otros diseños especializados', '541490'),
  ('Diseño gráfico', '541430'),
  ('Diseño industrial', '541420'),
  ('Diseño y decoración de interiores', '541410'),
  ('Distribución de energía eléctrica', '221110'),
  ('Distribución de material publicitario', '541870'),
  ('Distribución de películas y de otros materiales audiovisuales', '512120'),
  ('Edición de directorios y listas de correo en formato electrónico', '511141'),
  ('Edición de directorios y listas de correo integrada con la impresión', '511142'),
  ('Edición de libros en formato electrónico', '513131'),
  ('Edición de libros integrada con la impresión', '511132'),
  ('Edición de otros materiales en formato electrónico', '513191'),
  ('Edición de periódicos en formato electrónico', '513111'),
  ('Edición de periódicos integrada con la impresión', '511112'),
  ('Edición de revistas y otras publicaciones periódicas en formato electrónico', '511121'),
  ('Edición de revistas y otras publicaciones periódicas integrada con la impresión', '513122'),
  ('Edición de software', '511210'),
  ('Edificación de inmuebles comerciales y de servicios, excepto la supervisión', '236221'),
  ('Edificación de naves y plantas industriales, excepto la supervisión', '236211'),
  ('Edificación de vivienda multifamiliar', '236112'),
  ('Edificación de vivienda unifamiliar', '236111'),
  ('Editoras de música', '512230'),
  ('Elaboración de aceites y grasas vegetales comestibles', '311222'),
  ('Elaboración de alimentos frescos para consumo inmediato', '311993'),
  ('Elaboración de alimentos para animales', '311110'),
  ('Elaboración de azúcar de caña', '311311'),
  ('Elaboración de bebidas alcohólicas a base de uva', '312131'),
  ('Elaboración de botanas', '311910'),
  ('Elaboración de café instantáneo', '311923'),
  ('Elaboración de café tostado y molido', '311922'),
  ('Elaboración de cereales para el desayuno', '311230'),
  ('Elaboración de cerveza', '312120'),
  ('Elaboración de chocolate y productos de chocolate', '311350'),
  ('Elaboración de cigarros', '312221'),
  ('Elaboración de concentrados, polvos, jarabes y esencias de sabor para bebidas', '311930'),
  ('Elaboración de condimentos y aderezos', '311940'),
  ('Elaboración de derivados y fermentos lácteos', '311513'),
  ('Elaboración de dulces, chicles y productos de confitería que no sean de chocolate', '311340'),
  ('Elaboración de féculas y otros almidones y sus derivados', '311221'),
  ('Elaboración de galletas y pastas para sopa', '311820'),
  ('Elaboración de harina de otros productos agrícolas', '311214'),
  ('Elaboración de harina de trigo', '311212'),
  ('Elaboración de helados y paletas', '311520'),
  ('Elaboración de hielo', '312113'),
  ('Elaboración de leche en polvo, condensada y evaporada', '311512'),
  ('Elaboración de leche líquida', '311511'),
  ('Elaboración de levadura', '311992'),
  ('Elaboración de malta', '311215'),
  ('Elaboración de manteca y otras grasas animales comestibles', '311614'),
  ('Elaboración de mezcal', '312142'),
  ('Elaboración de otras bebidas destiladas', '312149'),
  ('Elaboración de otros alimentos', '311999'),
  ('Elaboración de otros azúcares', '311319'),
  ('Elaboración de pulque', '312132'),
  ('Elaboración de puros y otros productos de tabaco', '312222'),
  ('Elaboración de refrescos y otras bebidas no alcohólicas', '312111'),
  ('Elaboración de ron y otras bebidas destiladas de caña', '312141'),
  ('Elaboración de sidra y otras bebidas fermentadas', '312139'),
  ('Elaboración de tortillas de harina de trigo de forma tradicional', '311813'),
  ('Elaboración de tortillas de maíz y molienda de nixtamal', '311830'),
  ('Equipos deportivos profesionales', '711212'),
  ('Escuelas de arte del sector privado', '611611'),
  ('Escuelas de computación del sector privado', '611421'),
  ('Escuelas de computación del sector público', '611422'),
  ('Escuelas de deporte del sector privado', '611621'),
  ('Escuelas de deporte del sector público', '611622'),
  ('Escuelas de educación media superior del sector privado', '611161'),
  ('Escuelas de educación media superior del sector público', '611162'),
  ('Escuelas de educación media técnica terminal del sector privado', '611151'),
  ('Escuelas de educación preescolar del sector privado', '611111'),
  ('Escuelas de educación preescolar del sector público', '611112'),
  ('Escuelas de educación primaria del sector privado', '611121'),
  ('Escuelas de educación primaria del sector público', '611122'),
  ('Escuelas de educación secundaria general del sector privado', '611131'),
  ('Escuelas de educación secundaria general del sector público', '611132'),
  ('Escuelas de educación secundaria técnica del sector privado', '611141'),
  ('Escuelas de educación secundaria técnica del sector público', '611142'),
  ('Escuelas de educación superior del sector privado', '611311'),
  ('Escuelas de educación superior del sector público', '611312'),
  ('Escuelas de educación técnica superior del sector privado', '611211'),
  ('Escuelas de educación técnica superior del sector público', '611212'),
  ('Escuelas de idiomas del sector privado', '611631'),
  ('Escuelas de idiomas del sector público', '611632'),
  ('Escuelas del sector privado de educación para necesidades especiales', '611181'),
  ('Escuelas del sector privado dedicadas a la enseñanza de oficios', '611511'),
  ('Escuelas del sector privado que combinan diversos niveles de educación', '611171'),
  ('Escuelas del sector público de educación para necesidades especiales', '611182'),
  ('Escuelas del sector público dedicadas a la enseñanza de oficios', '611512'),
  ('Escuelas del sector público que combinan diversos niveles de educación', '611172'),
  ('Escuelas para la capacitación de ejecutivos del sector privado', '611431'),
  ('Estacionamientos y pensiones para vehículos automotores', '812410'),
  ('Estaciones de transmisión de programas de radio', '515110'),
  ('Estaciones de transmisión de programas de televisión', '515120'),
  ('Exhibición de películas y otros materiales audiovisuales', '512130'),
  ('Extracción de petróleo y gas natural asociado', '211110'),
  ('Fabricación de aceites y grasas lubricantes', '324191'),
  ('Fabricación de acumuladores y pilas', '335910'),
  ('Fabricación de adhesivos', '325520'),
  ('Fabricación de alambre, productos de alambre y resortes', '332610'),
  ('Fabricación de alfombras y tapetes', '314110'),
  ('Fabricación de anuncios y señalamientos', '339950'),
  ('Fabricación de aparatos de línea blanca', '335220'),
  ('Fabricación de aparatos e instrumentos para pesar', '333993'),
  ('Fabricación de artículos de alfarería, porcelana y loza', '327111'),
  ('Fabricación de artículos de vidrio de uso doméstico', '327215'),
  ('Fabricación de artículos de vidrio de uso industrial y comercial', '327216'),
  ('Fabricación de artículos deportivos', '339920'),
  ('Fabricación de artículos oftálmicos', '339113'),
  ('Fabricación de artículos y accesorios para escritura, pintura, dibujo y actividades de oficina', '339940'),
  ('Fabricación de artículos y utensilios de madera para el hogar', '321992'),
  ('Fabricación de asientos y accesorios interiores para vehículos automotores', '336360'),
  ('Fabricación de ataúdes', '339995'),
  ('Fabricación de automóviles y camionetas', '336110'),
  ('Fabricación de autopartes de plástico con y sin reforzamiento', '326192'),
  ('Fabricación de azulejos y losetas no refractarias', '327122'),
  ('Fabricación de baleros y rodamientos', '332991'),
  ('Fabricación de bandas y mangueras de hule y de plástico', '326220'),
  ('Fabricación de bicicletas y triciclos', '336992'),
  ('Fabricación de bolsas de papel y productos celulósicos recubiertos y tratados', '322220'),
  ('Fabricación de bolsas y películas de plástico flexible', '326110'),
  ('Fabricación de bolsos de mano, maletas y similares', '316991'),
  ('Fabricación de bombas y sistemas de bombeo', '333910'),
  ('Fabricación de botellas de plástico', '326160'),
  ('Fabricación de cables de conducción eléctrica', '335920'),
  ('Fabricación de cal', '327410'),
  ('Fabricación de calcetines y medias de tejido de punto', '315121'),
  ('Fabricación de calderas industriales', '332410'),
  ('Fabricación de calzado con corte de piel y cuero', '316211'),
  ('Fabricación de calzado con corte de tela', '316212'),
  ('Fabricación de calzado de hule', '316214'),
  ('Fabricación de calzado de plástico', '316213'),
  ('Fabricación de camiones y tractocamiones', '336120'),
  ('Fabricación de carrocerías y remolques', '336210'),
  ('Fabricación de cartón y cartoncillo a partir de pulpa', '322132'),
  ('Fabricación de cemento y productos a base de cemento en plantas integradas', '327310'),
  ('Fabricación de cerillos', '325991'),
  ('Fabricación de cierres, botones y agujas', '339992'),
  ('Fabricación de cocinas integrales y muebles modulares de baño', '337110'),
  ('Fabricación de colchones', '337910'),
  ('Fabricación de componentes electrónicos', '334410'),
  ('Fabricación de computadoras y equipo periférico', '334110'),
  ('Fabricación de concreto', '327320'),
  ('Fabricación de cosméticos, perfumes y otras preparaciones de tocador', '325620'),
  ('Fabricación de desbastes primarios y ferroaleaciones', '331112'),
  ('Fabricación de embarcaciones', '336610'),
  ('Fabricación de enchufes, contactos, fusibles y otros accesorios para instalaciones eléctricas', '335930'),
  ('Fabricación de enseres electrodomésticos menores', '335210'),
  ('Fabricación de envases de cartón', '322210'),
  ('Fabricación de envases metálicos de calibre ligero', '332430'),
  ('Fabricación de envases y ampolletas de vidrio', '327213'),
  ('Fabricación de envases y contenedores de plástico para embalaje con y sin reforzamiento', '326193'),
  ('Fabricación de equipo aeroespacial', '336410'),
  ('Fabricación de equipo de aire acondicionado y calefacción', '333411'),
  ('Fabricación de equipo de audio y de video', '334310'),
  ('Fabricación de equipo de refrigeración industrial y comercial', '333412'),
  ('Fabricación de equipo de transmisión y recepción de señales de radio y televisión, y equipo de comunicación inalámbrico', '334220'),
  ('Fabricación de equipo eléctrico y electrónico y sus partes para vehículos automotores', '336320'),
  ('Fabricación de equipo ferroviario', '336510'),
  ('Fabricación de equipo no electrónico para uso médico, dental y para laboratorio', '339111'),
  ('Fabricación de equipo para soldar y soldaduras', '333991'),
  ('Fabricación de equipo telefónico', '334210'),
  ('Fabricación de equipo y aparatos de distribución de energía eléctrica', '335312'),
  ('Fabricación de escobas, cepillos y similares', '339993'),
  ('Fabricación de espumas y productos de poliestireno', '326140'),
  ('Fabricación de espumas y productos de uretano', '326150'),
  ('Fabricación de estructuras metálicas', '332310'),
  ('Fabricación de explosivos', '325920'),
  ('Fabricación de fertilizantes', '325310'),
  ('Fabricación de fibras químicas', '325220'),
  ('Fabricación de focos', '335110'),
  ('Fabricación de gases industriales', '325120'),
  ('Fabricación de herrajes y cerraduras', '332510'),
  ('Fabricación de herramientas de mano metálicas sin motor', '332211'),
  ('Fabricación de hilos para coser y bordar', '313113'),
  ('Fabricación de huaraches y calzado de otro tipo de materiales', '316219'),
  ('Fabricación de hules sintéticos', '325212'),
  ('Fabricación de instrumentos musicales', '339991'),
  ('Fabricación de jabones, limpiadores y dentífricos', '325610'),
  ('Fabricación de juguetes', '339930'),
  ('Fabricación de ladrillos no refractarios', '327121'),
  ('Fabricación de laminados de plástico rígido', '326130'),
  ('Fabricación de laminados y aglutinados de madera', '321210'),
  ('Fabricación de lámparas ornamentales', '335120'),
  ('Fabricación de llantas y cámaras', '326211'),
  ('Fabricación de maquinaria y equipo agrícola', '333111'),
  ('Fabricación de maquinaria y equipo para envasar y empacar', '333992'),
  ('Fabricación de maquinaria y equipo para la construcción', '333120'),
  ('Fabricación de maquinaria y equipo para la industria alimentaria y de las bebidas', '333243'),
  ('Fabricación de maquinaria y equipo para la industria de la impresión', '333245'),
  ('Fabricación de maquinaria y equipo para la industria de la madera', '333241'),
  ('Fabricación de maquinaria y equipo para la industria del hule y del plástico', '333242'),
  ('Fabricación de maquinaria y equipo para la industria del vidrio y otros minerales no metálicos', '333246'),
  ('Fabricación de maquinaria y equipo para la industria extractiva', '333130'),
  ('Fabricación de maquinaria y equipo para la industria metalmecánica', '333510'),
  ('Fabricación de maquinaria y equipo para la industria textil', '333244'),
  ('Fabricación de maquinaria y equipo para levantar y trasladar', '333920'),
  ('Fabricación de maquinaria y equipo para otras industrias manufactureras', '333249'),
  ('Fabricación de maquinaria y equipo pecuario', '333112'),
  ('Fabricación de material desechable de uso médico', '339112'),
  ('Fabricación de materias primas para la industria farmacéutica', '325411'),
  ('Fabricación de motocicletas', '336991'),
  ('Fabricación de motores de combustión interna, turbinas y transmisiones', '333610'),
  ('Fabricación de motores de gasolina y sus partes para vehículos automotrices', '336310'),
  ('Fabricación de motores y generadores eléctricos', '335311'),
  ('Fabricación de muebles de baño', '327112'),
  ('Fabricación de muebles de oficina y estantería', '337210'),
  ('Fabricación de muebles, excepto cocinas integrales, muebles modulares de baño y muebles de oficina y estantería', '337120'),
  ('Fabricación de otra maquinaria y equipo para el comercio y los servicios', '333319'),
  ('Fabricación de otra maquinaria y equipo para la industria en general', '333999'),
  ('Fabricación de otras partes para vehículos automotrices', '336390'),
  ('Fabricación de otro equipo de transporte', '336999'),
  ('Fabricación de otros equipos de comunicación', '334290'),
  ('Fabricación de otros instrumentos de medición, control, navegación, y equipo médico electrónico', '334519'),
  ('Fabricación de otros productos a base de minerales no metálicos', '327999'),
  ('Fabricación de otros productos de cartón y papel', '322299'),
  ('Fabricación de otros productos de cemento y concreto', '327399'),
  ('Fabricación de otros productos de cuero, piel y materiales sucedáneos', '316999'),
  ('Fabricación de otros productos de hierro y acero', '331220'),
  ('Fabricación de otros productos de hule', '326290'),
  ('Fabricación de otros productos de madera', '321999'),
  ('Fabricación de otros productos de plástico con reforzamiento', '326198'),
  ('Fabricación de otros productos de plástico de uso industrial sin reforzamiento', '326194'),
  ('Fabricación de otros productos de plástico sin reforzamiento', '326199'),
  ('Fabricación de otros productos de vidrio', '327219'),
  ('Fabricación de otros productos eléctricos', '335999'),
  ('Fabricación de otros productos metálicos', '332999'),
  ('Fabricación de otros productos químicos', '325999'),
  ('Fabricación de otros productos químicos básicos inorgánicos', '325180'),
  ('Fabricación de otros productos químicos básicos orgánicos', '325190'),
  ('Fabricación de pañales desechables y productos sanitarios', '322291'),
  ('Fabricación de papel a partir de pulpa', '322122'),
  ('Fabricación de partes de sistemas de dirección y de suspensión para vehículos automotrices', '336330'),
  ('Fabricación de partes de sistemas de frenos para vehículos automotrices', '336340'),
  ('Fabricación de partes de sistemas de transmisión para vehículos automotores', '336350'),
  ('Fabricación de películas, placas y papel fotosensible para fotografía', '325992'),
  ('Fabricación de persianas y cortineros', '337920'),
  ('Fabricación de pesticidas y otros agroquímicos, excepto fertilizantes', '325320'),
  ('Fabricación de petroquímicos básicos del gas natural y del petróleo refinado', '325110'),
  ('Fabricación de piezas metálicas troqueladas para vehículos automotrices', '336370'),
  ('Fabricación de pigmentos y colorantes sintéticos', '325130'),
  ('Fabricación de pinturas y recubrimientos', '325510'),
  ('Fabricación de preparaciones farmacéuticas', '325412'),
  ('Fabricación de productos a base de piedras de cantera', '327991'),
  ('Fabricación de productos abrasivos', '327910'),
  ('Fabricación de productos de asfalto', '324120'),
  ('Fabricación de productos de herrería', '332320'),
  ('Fabricación de productos de madera de uso industrial', '321993'),
  ('Fabricación de productos de madera para la construcción', '321910'),
  ('Fabricación de productos de materiales trenzables, excepto palma', '321991'),
  ('Fabricación de productos de papelería', '322230'),
  ('Fabricación de productos de plástico para el hogar con y sin reforzamiento', '326191'),
  ('Fabricación de productos eléctricos de carbón y grafito', '335991'),
  ('Fabricación de productos metálicos forjados y troquelados', '332110'),
  ('Fabricación de productos para embalaje y envases de madera', '321920'),
  ('Fabricación de productos preesforzados de concreto', '327391'),
  ('Fabricación de productos textiles reciclados', '314993'),
  ('Fabricación de redes y otros productos de cordelería', '314992'),
  ('Fabricación de relojes', '334511'),
  ('Fabricación de resinas de plásticos reciclados', '325993'),
  ('Fabricación de resinas sintéticas', '325211'),
  ('Fabricación de ropa exterior de tejido de punto', '315123'),
  ('Fabricación de ropa interior de tejido de punto', '315122'),
  ('Fabricación de tanques metálicos de calibre grueso', '332420'),
  ('Fabricación de telas anchas de tejido de trama', '313210'),
  ('Fabricación de telas de tejido de punto', '313240'),
  ('Fabricación de telas no tejidas (comprimidas)', '313230'),
  ('Fabricación de telas recubiertas', '313320'),
  ('Fabricación de tintas para impresión', '325910'),
  ('Fabricación de tornillos, tuercas, remaches y similares', '332720'),
  ('Fabricación de tubería y conexiones, y tubos para embalaje', '326120'),
  ('Fabricación de tubos y bloques de cemento y concreto', '327330'),
  ('Fabricación de tubos y postes de hierro y acero', '331210'),
  ('Fabricación de utensilios de cocina metálicos', '332212'),
  ('Fabricación de válvulas metálicas', '332910'),
  ('Fabricación de velas y veladoras', '339994'),
  ('Fabricación de yeso y productos de yeso', '327420'),
  ('Fabricación y reproducción de medios magnéticos y ópticos', '334610'),
  ('Farmacias con minisúper', '464112'),
  ('Farmacias sin minisúper', '464111'),
  ('Fondos de aseguramiento campesino', '524120'),
  ('Fondos y fideicomisos financieros', '522220'),
  ('Fundición y refinación de metales preciosos', '331412'),
  ('Fundición y refinación de otros metales no ferrosos', '331419'),
  ('Generación de electricidad a partir de energía eólica', '221114'),
  ('Generación de electricidad a partir de energía solar', '221113'),
  ('Grabación de discos compactos (CD) y de video digital (DVD) o casetes musicales', '512240'),
  ('Grupos musicales del sector público', '711132'),
  ('Grutas, parques naturales y otros sitios del patrimonio cultural de la nación', '712190'),
  ('Guarderías del sector privado', '624411'),
  ('Guarderías del sector público', '624412'),
  ('Hojalatería y pintura de automóviles y camiones', '811121'),
  ('Hospitales del sector privado de otras especialidades médicas', '622311'),
  ('Hospitales del sector público de otras especialidades médicas', '622312'),
  ('Hospitales generales del sector privado', '622111'),
  ('Hospitales generales del sector público', '622112'),
  ('Hospitales psiquiátricos y para el tratamiento por adicción del sector público', '622212'),
  ('Hoteles con otros servicios integrados', '721111'),
  ('Hoteles sin otros servicios integrados', '721112'),
  ('Impresión de formas continuas y otros impresos', '323119'),
  ('Impresión de libros, periódicos y revistas', '323111'),
  ('Industria básica del aluminio', '331310'),
  ('Industrias conexas a la impresión', '323120'),
  ('Inmobiliarias y corredores de bienes raíces', '531210'),
  ('Instalación de cristales y otras reparaciones a la carrocería de automóviles y camiones', '811129'),
  ('Instalación de señalamientos y protecciones en obras viales', '237311'),
  ('Instalaciones de sistemas centrales de aire acondicionado y calefacción', '238222'),
  ('Instalaciones eléctricas en construcciones', '238210'),
  ('Instalaciones hidrosanitarias y de gas', '238221'),
  ('Intermediación de comercio al por mayor de productos agropecuarios', '437311'),
  ('Intermediación de comercio al por mayor de productos de uso doméstico y personal', '437113'),
  ('Intermediación de comercio al por mayor de productos para la industria, el comercio y los servicios', '437312'),
  ('Jardines botánicos y zoológicos del sector privado', '712131'),
  ('Jardines botánicos y zoológicos del sector público', '712132'),
  ('Joyería de metales y piedras no preciosos y de otros materiales', '339913'),
  ('Laboratorios de pruebas', '541380'),
  ('Laboratorios médicos y de diagnóstico del sector privado', '621511'),
  ('Laboratorios médicos y de diagnóstico del sector público', '621512'),
  ('Laminación secundaria de cobre', '331420'),
  ('Laminación secundaria de otros metales no ferrosos', '331490'),
  ('Lavado y lubricado de automóviles y camiones', '811192'),
  ('Lavanderías y tintorerías', '812210'),
  ('Manejo de residuos peligrosos y servicios de remediación a zonas dañadas por materiales o residuos peligrosos', '562111'),
  ('Mantenimiento de la seguridad y el orden público', '931410'),
  ('Maquinado de piezas metálicas para maquinaria y equipo en general', '332710'),
  ('Marinas turísticas', '713930'),
  ('Matanza de ganado, aves y otros animales comestibles', '311611'),
  ('Metalistería de metales no preciosos', '339914'),
  ('Minería de arena y grava para la construcción', '212321'),
  ('Minería de barita', '212393'),
  ('Minería de caolín', '212325'),
  ('Minería de carbón mineral', '212110'),
  ('Minería de cobre', '212231'),
  ('Minería de feldespato', '212323'),
  ('Minería de fluorita', '212395'),
  ('Minería de grafito', '212396'),
  ('Minería de hierro', '212210'),
  ('Minería de manganeso', '212291'),
  ('Minería de mármol', '212312'),
  ('Minería de mercurio y antimonio', '212292'),
  ('Minería de oro', '212221'),
  ('Minería de otras arcillas y de otros minerales refractarios', '212329'),
  ('Minería de otras piedras dimensionadas', '212319'),
  ('Minería de otros minerales metálicos', '212299'),
  ('Minería de otros minerales no metálicos', '212399'),
  ('Minería de piedra caliza', '212311'),
  ('Minería de piedra de yeso', '212392'),
  ('Minería de plata', '212222'),
  ('Minería de plomo y zinc', '212232'),
  ('Minería de roca fosfórica', '212394'),
  ('Minería de sal', '212391'),
  ('Minería de sílice', '212324'),
  ('Minería de tezontle y tepetate', '212322'),
  ('Moldeo por fundición de piezas de hierro y acero', '331510'),
  ('Moldeo por fundición de piezas metálicas no ferrosas', '331520'),
  ('Montaje de estructuras de acero prefabricadas', '238122'),
  ('Montaje de estructuras de concreto prefabricadas', '238121'),
  ('Montepíos', '522451'),
  ('Moteles', '721113'),
  ('Museos del sector privado', '712111'),
  ('Museos del sector público', '712112'),
  ('Notarías públicas', '541120'),
  ('Obtención de alcohol etílico potable', '312143'),
  ('Operadores de servicios de telecomunicaciones alámbricas', '517311'),
  ('Operadores de servicios de telecomunicaciones inalámbricas', '517312'),
  ('Orfanatos y otras residencias de asistencia social del sector privado', '623991'),
  ('Orfanatos y otras residencias de asistencia social del sector público', '623992'),
  ('Orfebrería y joyería de metales y piedras preciosos', '339912'),
  ('Organismos internacionales', '932110'),
  ('Organización de excursiones y paquetes turísticos para agencias de viajes', '561520'),
  ('Organizadores de convenciones y ferias comerciales e industriales', '561920'),
  ('Órganos legislativos', '931110'),
  ('Otras compañías y grupos de espectáculos artísticos del sector privado', '711191'),
  ('Otras industrias manufactureras', '339999'),
  ('Otras instalaciones y equipamiento en construcciones', '238290'),
  ('Otras instituciones de intermediación crediticia y financiera no bursátil', '522490'),
  ('Otras reparaciones mecánicas de automóviles y camiones', '811119'),
  ('Otro autotransporte foráneo de carga especializado', '484239'),
  ('Otro autotransporte foráneo de carga general', '484129'),
  ('Otro autotransporte local de carga especializado', '484229'),
  ('Otro autotransporte local de carga general', '484119'),
  ('Otro transporte terrestre de pasajeros', '485990'),
  ('Otro transporte turístico', '487990'),
  ('Otros centros del sector privado para la atención de pacientes que no requieren hospitalización', '621491'),
  ('Otros consultorios del sector privado para el cuidado de la salud', '621398'),
  ('Otros juegos de azar', '713299'),
  ('Otros servicios de almacenamiento con instalaciones especializadas', '493190'),
  ('Otros servicios de almacenamiento general sin instalaciones especializadas', '493119'),
  ('Otros servicios de apoyo a los negocios', '561990'),
  ('Otros servicios de consultoría científica y técnica', '541690'),
  ('Otros servicios de grabación del sonido', '512290'),
  ('Otros servicios de intermediación para el transporte de carga', '488519'),
  ('Otros servicios de limpieza', '561790'),
  ('Otros servicios de manejo de residuos por el sector privado', '562998'),
  ('Otros servicios de manejo de residuos por el sector público', '562999'),
  ('Otros servicios de orientación y trabajo social prestados por el sector privado', '624198'),
  ('Otros servicios de orientación y trabajo social prestados por el sector público', '624199'),
  ('Otros servicios de reparación y mantenimiento de automóviles y camiones', '811199'),
  ('Otros servicios de reservaciones', '561590'),
  ('Otros servicios de telecomunicaciones', '517910'),
  ('Otros servicios educativos proporcionados por el sector privado', '611698'),
  ('Otros servicios personales', '812990'),
  ('Otros servicios profesionales, científicos y técnicos', '541990'),
  ('Otros servicios recreativos prestados por el sector privado', '713998'),
  ('Otros servicios relacionados con el transporte', '488990'),
  ('Otros servicios relacionados con el transporte aéreo', '488190'),
  ('Otros servicios relacionados con el transporte por agua', '488390'),
  ('Otros servicios relacionados con la agricultura', '115119'),
  ('Otros servicios relacionados con la contabilidad', '541219'),
  ('Otros servicios relacionados con la intermediación bursátil', '523990'),
  ('Otros servicios relacionados con la minería', '213119'),
  ('Otros servicios relacionados con los servicios inmobiliarios', '531319'),
  ('Otros trabajos de acabados en edificaciones', '238390'),
  ('Otros trabajos en exteriores', '238190'),
  ('Otros trabajos especializados para la construcción', '238990'),
  ('Panificación tradicional', '311812'),
  ('Parques acuáticos y balnearios del sector privado', '713113'),
  ('Parques acuáticos y balnearios del sector público', '713114'),
  ('Parques de diversiones y temáticos del sector privado', '713111'),
  ('Parques de diversiones y temáticos del sector público', '713112'),
  ('Pensiones y casas de huéspedes', '721311'),
  ('Perforación de pozos petroleros y de gas', '213111'),
  ('Pesca de camarón', '114111'),
  ('Pesca de sardina y anchoveta', '114113'),
  ('Pesca de túnidos', '114112'),
  ('Pesca y captura de peces, crustáceos, moluscos y otras especies', '114119'),
  ('Piscicultura en agua dulce', '112512'),
  ('Piscicultura en agua salada', '112516'),
  ('Portales de búsqueda en la red y otros servicios de suministro de información', '519290'),
  ('Preparación de embutidos y otras conservas de carne de ganado, aves y otros animales comestibles', '311613'),
  ('Preparación de terrenos para la construcción', '238910'),
  ('Preparación e hilado de fibras blandas naturales', '313112'),
  ('Preparación e hilado de fibras duras naturales', '313111'),
  ('Preparación y envasado de pescados y mariscos', '311710'),
  ('Preparación y envasado de té', '311924'),
  ('Procesamiento electrónico de información, hospedaje y otros servicios relacionados', '518210'),
  ('Producción de películas', '512111'),
  ('Producción de programas para la televisión', '512112'),
  ('Producción de videoclips, comerciales y otros materiales audiovisuales', '512113'),
  ('Productoras y distribuidoras discográficas', '512250'),
  ('Promotores de espectáculos artísticos, culturales, deportivos y similares que no cuentan con instalaciones para presentarlos', '711320'),
  ('Promotores del sector privado de espectáculos artísticos, culturales, deportivos y similares que cuentan con instalaciones para presentarlos', '711311'),
  ('Promotores del sector público de espectáculos artísticos, culturales, deportivos y similares que cuentan con instalaciones para presentarlos', '711312'),
  ('Purificación y embotellado de agua', '312112'),
  ('Realización de trabajos de carpintería en el lugar de la construcción', '238350'),
  ('Recolección de residuos no peligrosos por el sector privado', '562121'),
  ('Recolección de residuos no peligrosos por el sector público', '562122'),
  ('Rectificación de partes de motor de automóviles y camiones', '811113'),
  ('Recubrimientos y terminados metálicos', '332810'),
  ('Recuperación de residuos por el sector privado', '562921'),
  ('Recuperación de residuos por el sector público', '562922'),
  ('Refinación de petróleo', '324110'),
  ('Refugios temporales comunitarios del sector privado', '624221'),
  ('Refugios temporales comunitarios del sector público', '624222'),
  ('Regulación y fomento de actividades para mejorar y preservar el medio ambiente', '931510'),
  ('Regulación y fomento del desarrollo económico', '931310'),
  ('Relaciones exteriores', '931710'),
  ('Reparación de calzado y otros artículos de piel y cuero', '811430'),
  ('Reparación de suspensiones de automóviles y camiones', '811115'),
  ('Reparación de tapicería de muebles para el hogar', '811420'),
  ('Reparación de transmisiones de automóviles y camiones', '811114'),
  ('Reparación del sistema eléctrico de automóviles y camiones', '811112'),
  ('Reparación mecánica en general de automóviles y camiones', '811111'),
  ('Reparación menor de llantas', '811191'),
  ('Reparación y mantenimiento de aparatos eléctricos para el hogar y personales', '811410'),
  ('Reparación y mantenimiento de bicicletas', '811493'),
  ('Reparación y mantenimiento de equipo electrónico de uso doméstico', '811211'),
  ('Reparación y mantenimiento de maquinaria y equipo agropecuario y forestal', '811311'),
  ('Reparación y mantenimiento de maquinaria y equipo comercial y de servicios', '811314'),
  ('Reparación y mantenimiento de maquinaria y equipo industrial', '811312'),
  ('Reparación y mantenimiento de maquinaria y equipo para mover, levantar y acomodar materiales', '811313'),
  ('Reparación y mantenimiento de motocicletas', '811492'),
  ('Reparación y mantenimiento de otro equipo electrónico y de equipo de precisión', '811219'),
  ('Reparación y mantenimiento de otros artículos para el hogar y personales', '811499'),
  ('Residencias del sector privado con cuidados de enfermeras para enfermos convalecientes, en rehabilitación, incurables y terminales', '623111'),
  ('Residencias del sector privado para el cuidado de personas con problemas de retardo mental', '623211'),
  ('Residencias del sector privado para el cuidado de personas con problemas de trastorno mental y adicción', '623221'),
  ('Residencias del sector público con cuidados de enfermeras para enfermos convalecientes, en rehabilitación, incurables y terminales', '623112'),
  ('Residencias del sector público para el cuidado de personas con problemas de retardo mental', '623212'),
  ('Residencias del sector público para el cuidado de personas con problemas de trastorno mental y adicción', '623222'),
  ('Restaurantes con servicio de preparación de alimentos a la carta o de comida corrida', '722511'),
  ('Restaurantes con servicio de preparación de antojitos', '722513'),
  ('Restaurantes con servicio de preparación de pescados y mariscos', '722512'),
  ('Restaurantes con servicio de preparación de pizzas, hamburguesas, hot dogs y pollos rostizados para llevar', '722517'),
  ('Restaurantes con servicio de preparación de tacos y tortas', '722514'),
  ('Restaurantes de autoservicio', '722516'),
  ('Restaurantes que preparan otro tipo de alimentos para llevar', '722518'),
  ('Revitalización de llantas', '326212'),
  ('Salones y clínicas de belleza y peluquerías', '812110'),
  ('Sanitarios públicos y bolerías', '812130'),
  ('Servicios a la navegación aérea', '488111'),
  ('Servicios combinados de apoyo en instalaciones', '561210'),
  ('Servicios de acceso a computadoras', '561432'),
  ('Servicios de administración de bienes raíces', '531311'),
  ('Servicios de administración de carreteras, puentes y servicios auxiliares', '488492'),
  ('Servicios de administración de centrales camioneras', '488491'),
  ('Servicios de administración de negocios', '561110'),
  ('Servicios de agencias aduanales', '488511'),
  ('Servicios de alimentación comunitarios prestados por el sector privado', '624211'),
  ('Servicios de alimentación comunitarios prestados por el sector público', '624212'),
  ('Servicios de alquiler de marcas registradas, patentes y franquicias', '533110'),
  ('Servicios de ambulancias', '621910'),
  ('Servicios de apoyo para efectuar trámites legales', '541190'),
  ('Servicios de arquitectura', '541310'),
  ('Servicios de arquitectura de paisaje y urbanismo', '541320'),
  ('Servicios de bancos de órganos, bancos de sangre y otros servicios auxiliares al tratamiento médico prestados por el sector privado', '621991'),
  ('Servicios de bancos de órganos, bancos de sangre y otros servicios auxiliares al tratamiento médico prestados por el sector público', '621992'),
  ('Servicios de báscula para el transporte y otros servicios relacionados con el transporte por carretera', '488493'),
  ('Servicios de blindaje y de adaptación de automóviles y camiones', '811123'),
  ('Servicios de capacitación para el trabajo prestados por el sector privado para personas desempleadas, subempleadas o discapacitadas', '624311'),
  ('Servicios de capacitación para el trabajo prestados por el sector público para personas desempleadas, subempleadas o discapacitadas', '624312'),
  ('Servicios de carga y descarga para el transporte por agua', '488320'),
  ('Servicios de casetas telefónicas', '561421'),
  ('Servicios de comedor para empresas e instituciones', '722310'),
  ('Servicios de consultoría en administración', '541610'),
  ('Servicios de consultoría en medio ambiente', '541620'),
  ('Servicios de contabilidad y auditoría', '541211'),
  ('Servicios de control y exterminación de plagas', '561710'),
  ('Servicios de dibujo', '541340'),
  ('Servicios de diseño de sistemas de cómputo y servicios relacionados', '541510'),
  ('Servicios de distribución de audio y video en tiempo real (streaming), redes sociales, cadenas de radio y televisión y otros proveedores de contenido', '516210'),
  ('Servicios de elaboración de mapas', '541370'),
  ('Servicios de emergencia comunitarios prestados por el sector privado', '624231'),
  ('Servicios de emergencia comunitarios prestados por el sector público', '624232'),
  ('Servicios de empacado y etiquetado', '561910'),
  ('Servicios de enfermería a domicilio', '621610'),
  ('Servicios de fotocopiado, fax y afines', '561431'),
  ('Servicios de fotografía y videograbación', '541920'),
  ('Servicios de fumigación agrícola', '115111'),
  ('Servicios de grúa', '488410'),
  ('Servicios de ingeniería', '541330'),
  ('Servicios de inspección de edificios', '541350'),
  ('Servicios de instalación y mantenimiento de áreas verdes', '561730'),
  ('Servicios de investigación científica y desarrollo en ciencias naturales y exactas, ingeniería, y ciencias de la vida, prestados por el sector privado', '541711'),
  ('Servicios de investigación científica y desarrollo en ciencias naturales y exactas, ingeniería, y ciencias de la vida, prestados por el sector público', '541712'),
  ('Servicios de investigación científica y desarrollo en ciencias sociales y humanidades, prestados por el sector privado', '541721'),
  ('Servicios de investigación científica y desarrollo en ciencias sociales y humanidades, prestados por el sector público', '541722'),
  ('Servicios de investigación de mercados y encuestas de opinión pública', '541910'),
  ('Servicios de investigación y de protección y custodia, excepto mediante monitoreo', '561610'),
  ('Servicios de levantamiento geofísico', '541360'),
  ('Servicios de limpieza de inmuebles', '561720'),
  ('Servicios de limpieza de tapicería, alfombras y muebles', '561740'),
  ('Servicios de mensajería y paquetería foránea', '492110'),
  ('Servicios de mensajería y paquetería local', '492210'),
  ('Servicios de mudanzas', '484210'),
  ('Servicios de orientación y trabajo social para la niñez y la juventud prestados por el sector privado', '624111'),
  ('Servicios de orientación y trabajo social para la niñez y la juventud prestados por el sector público', '624112'),
  ('Servicios de postproducción y otros servicios para la industria fílmica y del video', '512190'),
  ('Servicios de preparación de alimentos en unidades móviles', '722330'),
  ('Servicios de preparación de alimentos para ocasiones especiales', '722320'),
  ('Servicios de preparación de documentos', '561410'),
  ('Servicios de preparación de otros alimentos para consumo inmediato', '722519'),
  ('Servicios de profesores particulares', '611691'),
  ('Servicios de protección y custodia mediante el monitoreo de sistemas de seguridad', '561620'),
  ('Servicios de recepción de llamadas telefónicas y promoción por teléfono', '561422'),
  ('Servicios de remediación de residuos por el sector privado', '562911'),
  ('Servicios de revelado e impresión de fotografías', '812910'),
  ('Servicios de rotulación y otros servicios de publicidad', '541890'),
  ('Servicios de traducción e interpretación', '541930'),
  ('Servicios funerarios', '812310'),
  ('Servicios para la navegación por agua', '488330'),
  ('Servicios postales', '491110'),
  ('Servicios relacionados con el aprovechamiento forestal', '115310'),
  ('Servicios relacionados con el transporte por ferrocarril', '488210'),
  ('Servicios relacionados con la cría y explotación de animales', '115210'),
  ('Servicios relacionados con la intermediación crediticia no bursátil', '522510'),
  ('Servicios veterinarios para la ganadería prestados por el sector privado', '541943'),
  ('Servicios veterinarios para la ganadería prestados por el sector público', '541944'),
  ('Servicios veterinarios para mascotas prestados por el sector privado', '541941'),
  ('Servicios veterinarios para mascotas prestados por el sector público', '541942'),
  ('Sitios históricos', '712120'),
  ('Sociedades financieras de objeto múltiple', '522460'),
  ('Suministro de personal permanente', '561330'),
  ('Supervisión de construcción de obras de generación y conducción de energía eléctrica y de obras para telecomunicaciones', '237133'),
  ('Supervisión de construcción de obras para el tratamiento, distribución y suministro de agua, drenaje y riego', '237113'),
  ('Supervisión de construcción de obras para petróleo y gas', '237123'),
  ('Supervisión de construcción de otras obras de ingeniería civil', '237994'),
  ('Supervisión de construcción de vías de comunicación', '237313'),
  ('Supervisión de división de terrenos y de construcción de obras de urbanización', '237213'),
  ('Supervisión de edificación de inmuebles comerciales y de servicios', '236222'),
  ('Supervisión de edificación de naves y plantas industriales', '236212'),
  ('Supervisión de edificación residencial', '236113'),
  ('Tapicería de automóviles y camiones', '811122'),
  ('Tenedoras de acciones', '551112'),
  ('Trabajos de albañilería', '238130'),
  ('Trabajos de cimentaciones', '238110'),
  ('Trabajos de enyesado, empastado y tiroleado', '238312'),
  ('Trabajos de pintura y otros cubrimientos de paredes', '238320'),
  ('Transporte aéreo no regular', '481210'),
  ('Transporte aéreo regular en líneas aéreas extranjeras', '481112'),
  ('Transporte aéreo regular en líneas aéreas nacionales', '481111'),
  ('Transporte colectivo foráneo de pasajeros de ruta fija', '485210'),
  ('Transporte colectivo urbano y suburbano de pasajeros en autobuses de ruta fija', '485111'),
  ('Transporte colectivo urbano y suburbano de pasajeros en autobuses que transitan en carril exclusivo', '485115'),
  ('Transporte colectivo urbano y suburbano de pasajeros en metro', '485114'),
  ('Transporte colectivo urbano y suburbano de pasajeros en trolebuses y trenes ligeros', '485113'),
  ('Transporte de gas natural por ductos', '486210'),
  ('Transporte de petróleo crudo por ductos', '486110'),
  ('Transporte escolar y de personal', '485410'),
  ('Transporte marítimo de altura, excepto de petróleo y gas natural', '483111'),
  ('Transporte marítimo de cabotaje, excepto de petróleo y gas natural', '483112'),
  ('Transporte marítimo de petróleo y gas natural', '483113'),
  ('Transporte por aguas interiores', '483210'),
  ('Transporte por ductos de productos refinados del petróleo', '486910'),
  ('Transporte por ferrocarril', '482110'),
  ('Transporte turístico por agua', '487210'),
  ('Transporte turístico por tierra', '487110'),
  ('Tratamiento de la madera y fabricación de postes y durmientes', '321113'),
  ('Tratamiento y disposición final de residuos no peligrosos por el sector privado', '562221'),
  ('Tratamiento y disposición final de residuos no peligrosos por el sector público', '562222'),
  ('Tratamiento y disposición final de residuos peligrosos por el sector privado', '562211'),
  ('Uniones de crédito', '522310'),
  ('Venta de billetes de lotería, pronósticos deportivos y otros boletos de sorteo', '713291');

ANALYZE scian_clase_catalog;

-- Mirror of extractMunicipio() in src/db/loader.ts.
CREATE FUNCTION pg_temp.denue_municipio(u text) RETURNS text
LANGUAGE sql IMMUTABLE AS $f$
  SELECT CASE
    WHEN u IS NULL THEN NULL
    WHEN cardinality(a) < 3 THEN nullif(a[1], '')
    ELSE nullif(coalesce(
      (SELECT string_agg(s, ', ' ORDER BY i)
         FROM unnest(a[1:cardinality(a) - 1]) WITH ORDINALITY AS m(s, i)
        WHERE s <> upper(s)),
      a[2]), '')
  END
  FROM (SELECT array_agg(trim(s) ORDER BY i) AS a
          FROM unnest(string_to_array(u, ',')) WITH ORDINALITY AS t(s, i)) p
$f$;

SELECT format($u$
UPDATE establecimientos e
   SET clase_actividad_id     = n.clase,
       sector_actividad_id    = left(n.clase, 2),
       subsector_actividad_id = left(n.clase, 3),
       rama_actividad_id      = left(n.clase, 4),
       subrama_actividad_id   = left(n.clase, 5),
       municipio              = n.municipio
  FROM (
    SELECT e2.id,
           coalesce(c.code, e2.clase_actividad_id) AS clase,
           pg_temp.denue_municipio(e2.ubicacion)   AS municipio
      FROM establecimientos e2
      LEFT JOIN scian_clase_catalog c ON c.label = e2.clase_actividad
     WHERE e2.entidad = %L
  ) n
 WHERE e.id = n.id
   AND (e.clase_actividad_id     IS DISTINCT FROM n.clase
     OR e.sector_actividad_id    IS DISTINCT FROM left(n.clase, 2)
     OR e.subsector_actividad_id IS DISTINCT FROM left(n.clase, 3)
     OR e.rama_actividad_id      IS DISTINCT FROM left(n.clase, 4)
     OR e.subrama_actividad_id   IS DISTINCT FROM left(n.clase, 5)
     OR e.municipio              IS DISTINCT FROM n.municipio)
$u$, entidad)
  FROM (SELECT DISTINCT entidad FROM establecimientos WHERE entidad IS NOT NULL) d
 ORDER BY entidad
\gexec
