/**
 * GET /tiles/:z/:x/:y.mvt — Mapbox Vector Tile endpoint for the analyzer map.
 *
 * Returns a binary MVT (application/x-protobuf) generated by PostGIS
 * ST_AsMVT directly — no pg_tileserv, no extra runtime dependency.
 *
 * Optional query filters:
 *  - entidad — 2-digit clave (01-32)
 *  - sector  — SCIAN filter. Either a single 2-digit code (legacy) or
 *    a comma-separated list of 2–6 digit codes at any depth (RH-5).
 *    Each code dispatches to its grain-matching indexed column on
 *    `establecimientos`: 2→sector_actividad_id, 3→subsector_actividad_id,
 *    4→rama_actividad_id, 5→subrama_actividad_id, 6→clase_actividad_id.
 *    Multi-code requests are combined as OR across the matched columns.
 *    Hard cap: MAX_SCIAN_CODES per request.
 *
 * Hard cap: TILE_FEATURE_CAP features per tile. Above that we sample
 * deterministically by ORDER BY clee LIMIT cap (clee has unique index,
 * so the cost is dominated by the bbox filter, not the sort).
 *
 * Auth: X-Api-Key (mounted in server.ts). Rate limit: 60 req/sec/IP
 * (mounted in server.ts via makeRateLimitMiddleware) — sized so a
 * single MapLibre viewport burst at zoom 5 (~28 parallel tile fetches)
 * doesn't run into 429s. The 50k-features-per-tile cap is the real
 * abuse defense.
 *
 * SQL composition is safe: every interpolated value is either a number
 * (parsed + bounded by Number.isInteger checks) or a 2–6 char numeric-
 * regex-validated string. There is no path for user input to reach SQL
 * unparsed.
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { Context } from "hono";

const execFileAsync = promisify(execFile);
import { HttpError } from "../middleware/error.js";
import {
  ENTIDAD_RE,
  MAX_TILE_ZOOM,
  TILE_FEATURE_CAP,
  type ApiServerConfig,
} from "../types.js";
import { assertSafeContainer } from "./_safe-container.js";

const TILE_CACHE_SECONDS = 3600;

/** Single SCIAN code at any of the 5 indexed depths. */
const SCIAN_MULTI_CODE_RE = /^[0-9]{2,6}$/;
/**
 * Defensive cap. Current bundle library tops out at 6 codes
 * (`educacion_particular`); 16 leaves ample headroom for ad-hoc
 * multi-bundle pickers and rejects accidental URL stuffing.
 */
const MAX_SCIAN_CODES = 16;

/**
 * Parse `sector` querystring into a list of validated SCIAN codes.
 * Accepts:
 *  - undefined / "" → no filter
 *  - single code: "46" or "4641"
 *  - comma-list:  "4641,46451,46411"
 * Whitespace around each token is trimmed; empty tokens are an error.
 */
export function parseSectorParam(raw: string | undefined): string[] | null {
  if (raw === undefined || raw === "") return null;
  const codes = raw.split(",").map((s) => s.trim());
  if (codes.length === 0 || codes.length > MAX_SCIAN_CODES) return null;
  for (const code of codes) {
    if (!SCIAN_MULTI_CODE_RE.test(code)) return null;
  }
  return codes;
}

/**
 * SCIAN depth → indexed column on `establecimientos`. Mirrors the
 * dispatch in `analytics.ts:2480-2502`.
 */
const SCIAN_COLUMN_BY_LENGTH: Record<number, string> = {
  2: "sector_actividad_id",
  3: "subsector_actividad_id",
  4: "rama_actividad_id",
  5: "subrama_actividad_id",
  6: "clase_actividad_id",
};

/**
 * Build the SQL filter clause for a validated SCIAN code list. Groups
 * codes by length so each group hits its grain-matching index, then
 * ORs the groups. Returns "" when no codes (caller treats as no-op).
 *
 * Exported for unit tests.
 */
export function buildSectorFilter(codes: string[]): string {
  if (codes.length === 0) return "";
  const byLen = new Map<number, string[]>();
  for (const code of codes) {
    const arr = byLen.get(code.length) ?? [];
    arr.push(code);
    byLen.set(code.length, arr);
  }
  const groups: string[] = [];
  for (const [len, list] of byLen.entries()) {
    const column = SCIAN_COLUMN_BY_LENGTH[len];
    if (!column) continue; // unreachable; length is regex-bounded 2..6
    const quoted = list.map((c) => `'${c}'`).join(", ");
    groups.push(`${column} IN (${quoted})`);
  }
  // Single group needs no outer parens; multi-group OR gets wrapped.
  return groups.length === 1
    ? `AND ${groups[0]}`
    : `AND (${groups.join(" OR ")})`;
}

export async function tilesHandler(
  c: Context,
  config: ApiServerConfig,
): Promise<Response> {
  const z = parseTileCoord(c.req.param("z"), "z", MAX_TILE_ZOOM);
  const x = parseTileCoord(c.req.param("x"), "x", 2 ** z - 1);
  const y = parseTileCoord(c.req.param("y"), "y", 2 ** z - 1);

  const entidad = c.req.query("entidad");
  if (entidad !== undefined && !ENTIDAD_RE.test(entidad)) {
    throw new HttpError(
      `entidad inválida "${entidad}"`,
      400,
      "validation.entidad",
    );
  }
  const sectorRaw = c.req.query("sector");
  let sectorCodes: string[] | null = null;
  if (sectorRaw !== undefined && sectorRaw !== "") {
    sectorCodes = parseSectorParam(sectorRaw);
    if (sectorCodes === null) {
      throw new HttpError(
        `sector inválido "${sectorRaw}" — debe ser hasta ${MAX_SCIAN_CODES} códigos SCIAN (2–6 dígitos), separados por coma`,
        400,
        "validation.sector",
      );
    }
  }

  const mvt = await buildTile(config, {
    z,
    x,
    y,
    ...(entidad !== undefined ? { entidad } : {}),
    ...(sectorCodes !== null ? { sectorCodes } : {}),
  });

  return new Response(mvt, {
    status: 200,
    headers: {
      "content-type": "application/x-protobuf",
      "cache-control": `public, max-age=${TILE_CACHE_SECONDS}`,
      // Vary on the auth headers so a downstream shared cache never serves
      // a tile from one principal to another. Lists both auth paths the
      // gateway accepts: Authorization (Bearer JWT, post-Phase-2 default)
      // and X-Api-Key (legacy/server-to-server). Phase 5 audit W3.
      vary: "Authorization, X-Api-Key",
      "x-tile-bytes": String(mvt.byteLength),
    },
  });
}

function parseTileCoord(
  raw: string | undefined,
  name: string,
  maxInclusive: number,
): number {
  if (raw === undefined || raw === "") {
    throw new HttpError(`tile ${name} faltante`, 400, "validation.tile");
  }
  // y may have a `.mvt` suffix from the route param; strip it.
  const cleaned = name === "y" ? raw.replace(/\.mvt$/, "") : raw;
  const n = Number(cleaned);
  if (
    !Number.isInteger(n) ||
    n < 0 ||
    n > maxInclusive ||
    !/^[0-9]+$/.test(cleaned)
  ) {
    throw new HttpError(
      `tile ${name} inválido "${raw}" — debe ser entero 0..${maxInclusive}`,
      400,
      "validation.tile",
    );
  }
  return n;
}

interface TileParams {
  z: number;
  x: number;
  y: number;
  entidad?: string;
  sectorCodes?: string[];
}

async function buildTile(
  config: ApiServerConfig,
  p: TileParams,
): Promise<ArrayBuffer> {
  assertSafeContainer(config.dbContainer);
  // Compose the WHERE additively so the SQL stays simple. All
  // interpolations are pre-validated integers or regex-bounded numeric
  // strings (2–6 digits).
  const filters: string[] = [];
  if (p.entidad) filters.push(`AND entidad = '${p.entidad}'`);
  if (p.sectorCodes && p.sectorCodes.length > 0) {
    filters.push(buildSectorFilter(p.sectorCodes));
  }
  const filterClause = filters.join(" ");

  // Tile envelope inlined as a literal expression on BOTH sides of the
  // pipeline so PostgreSQL can constant-fold at plan time. An earlier
  // version computed the envelope inside a CTE (bounds_3857 +
  // bounds_4326) which the planner treated as a runtime parameter ($1),
  // forcing a Bitmap Index Scan on idx_estab_geom that returned 3.6M
  // rows before applying the entidad/sector filters in heap recheck —
  // 60s per tile under the seeded entidad=09+sector=62 default. Inlining
  // lets the planner pick BitmapAnd(idx_estab_sector, idx_estab_entidad)
  // first (147ms) and only recheck the bbox in the heap. ~200x speedup.
  //
  // The prefilter `geom && ST_Transform(env, 4326)` MUST be SRID-aligned
  // or PostGIS compares raw bbox numbers and finds nothing (Web Mercator
  // coords are 1e6+, lat/lon ~180).
  //
  // ST_TileEnvelope is IMMUTABLE so duplicate calls fold to a single
  // constant during planning; no runtime cost from repeating it.
  const tileEnv3857 = `ST_TileEnvelope(${p.z}, ${p.x}, ${p.y})`;
  // LIMIT without ORDER BY — the planner short-circuits the scan as soon
  // as TILE_FEATURE_CAP matching rows are found, so an unfiltered low-
  // zoom tile completes in ~400ms instead of 16s. The trade-off is that
  // the sample is non-uniform (whatever the scan encounters first,
  // typically biased by physical row order which loosely correlates
  // with insert order = state). For density-heatmap visualization at
  // country zoom that's invisible; per-establishment markers at high
  // zoom never hit the cap because the bbox is small enough that all
  // matching rows fit. This is what enables the unfiltered "first
  // visit" experience to be fast without forcing default filters.
  const sql =
    `WITH filtered AS (` +
    `  SELECT clee, nombre, clase_actividad, geom` +
    `  FROM establecimientos` +
    `  WHERE 1=1 ${filterClause}` +
    `    AND geom && ST_Transform(${tileEnv3857}, 4326)` +
    `  LIMIT ${TILE_FEATURE_CAP}` +
    `), mvt_geom AS (` +
    `  SELECT ST_AsMVTGeom(ST_Transform(f.geom, 3857), ${tileEnv3857}, 4096, 64, true) AS geom,` +
    `         f.clee, f.nombre, f.clase_actividad` +
    `  FROM filtered f` +
    `) SELECT encode(ST_AsMVT(mvt_geom, 'establecimientos'), 'base64') FROM mvt_geom;`;

  let stdout: string;
  try {
    const result = await execFileAsync(
      "docker",
      [
        "exec",
        config.dbContainer,
        "psql",
        "-U",
        "postgres",
        "-d",
        "postgres",
        "-t",
        "-A",
        "-c",
        sql,
      ],
      {
        encoding: "utf-8",
        timeout: 30_000,
        maxBuffer: 50 * 1024 * 1024,
        // Audit C3-perf round-1 closure 2026-05-10: tile generation runs
        // ST_AsMVT on PostGIS-indexed geometry — typically <500ms but can
        // spike under high-density urban tiles. 25s backend timeout is
        // conservative; spawn timeout (30s) catches the kill cleanly.
        env: { ...process.env, PGOPTIONS: "-c statement_timeout=25000" },
      },
    );
    stdout = result.stdout.trim();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new HttpError(`tile generation failed: ${msg}`, 502, "postgis.error");
  }

  if (!stdout) {
    // Empty tile is valid — return a zero-byte MVT (empty layer).
    return new ArrayBuffer(0);
  }
  const buf = Buffer.from(stdout, "base64");
  // Slice off the parent ArrayBuffer to detach from any pooled storage and
  // give Response a clean BodyInit-compatible value.
  return buf.buffer.slice(
    buf.byteOffset,
    buf.byteOffset + buf.byteLength,
  ) as ArrayBuffer;
}
