/**
 * GET /tiles/:z/:x/:y.mvt — Mapbox Vector Tile endpoint for the analyzer map.
 *
 * Returns a binary MVT (application/x-protobuf) generated by PostGIS
 * ST_AsMVT directly — no pg_tileserv, no extra runtime dependency.
 *
 * Optional query filters:
 *  - entidad — 2-digit clave (01-32)
 *  - sector  — 2-digit SCIAN, filters on indexed `sector_actividad_id`
 *
 * Hard cap: TILE_FEATURE_CAP features per tile. Above that we sample
 * deterministically by ORDER BY clee LIMIT cap (clee has unique index,
 * so the cost is dominated by the bbox filter, not the sort).
 *
 * Auth: X-Api-Key (mounted in server.ts). Rate limit: 60 req/sec/IP
 * (mounted in server.ts via makeRateLimitMiddleware) — sized so a
 * single MapLibre viewport burst at zoom 5 (~28 parallel tile fetches)
 * doesn't run into 429s. The 50k-features-per-tile cap is the real
 * abuse defense.
 *
 * SQL composition is safe: every interpolated value is either a number
 * (parsed + bounded by Number.isInteger checks) or a 2-char regex-validated
 * string. There is no path for user input to reach SQL unparsed.
 */

import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { Context } from "hono";

const execFileAsync = promisify(execFile);
import { HttpError } from "../middleware/error.js";
import {
  ENTIDAD_RE,
  MAX_TILE_ZOOM,
  SCIAN_RE,
  TILE_FEATURE_CAP,
  type ApiServerConfig,
} from "../types.js";

const TILE_CACHE_SECONDS = 3600;

export async function tilesHandler(
  c: Context,
  config: ApiServerConfig,
): Promise<Response> {
  const z = parseTileCoord(c.req.param("z"), "z", MAX_TILE_ZOOM);
  const x = parseTileCoord(c.req.param("x"), "x", 2 ** z - 1);
  const y = parseTileCoord(c.req.param("y"), "y", 2 ** z - 1);

  const entidad = c.req.query("entidad");
  if (entidad !== undefined && !ENTIDAD_RE.test(entidad)) {
    throw new HttpError(
      `entidad inválida "${entidad}"`,
      400,
      "validation.entidad",
    );
  }
  const sector = c.req.query("sector");
  if (sector !== undefined && !SCIAN_RE.test(sector)) {
    throw new HttpError(
      `sector inválido "${sector}"`,
      400,
      "validation.sector",
    );
  }

  const mvt = await buildTile(config, {
    z,
    x,
    y,
    ...(entidad !== undefined ? { entidad } : {}),
    ...(sector !== undefined ? { sector } : {}),
  });

  return new Response(mvt, {
    status: 200,
    headers: {
      "content-type": "application/x-protobuf",
      "cache-control": `public, max-age=${TILE_CACHE_SECONDS}`,
      // Vary on the auth header so a downstream shared cache never serves
      // a tile from one API key to another.
      vary: "X-Api-Key",
      "x-tile-bytes": String(mvt.byteLength),
    },
  });
}

function parseTileCoord(
  raw: string | undefined,
  name: string,
  maxInclusive: number,
): number {
  if (raw === undefined || raw === "") {
    throw new HttpError(`tile ${name} faltante`, 400, "validation.tile");
  }
  // y may have a `.mvt` suffix from the route param; strip it.
  const cleaned = name === "y" ? raw.replace(/\.mvt$/, "") : raw;
  const n = Number(cleaned);
  if (
    !Number.isInteger(n) ||
    n < 0 ||
    n > maxInclusive ||
    !/^[0-9]+$/.test(cleaned)
  ) {
    throw new HttpError(
      `tile ${name} inválido "${raw}" — debe ser entero 0..${maxInclusive}`,
      400,
      "validation.tile",
    );
  }
  return n;
}

interface TileParams {
  z: number;
  x: number;
  y: number;
  entidad?: string;
  sector?: string;
}

async function buildTile(
  config: ApiServerConfig,
  p: TileParams,
): Promise<ArrayBuffer> {
  // Compose the WHERE additively so the SQL stays simple. All interpolations
  // are pre-validated integers or regex-bounded 2-char strings.
  const filters: string[] = [];
  if (p.entidad) filters.push(`AND entidad = '${p.entidad}'`);
  // sector_actividad_id is the backfilled, indexed copy of CLEE chars 6-7.
  if (p.sector) filters.push(`AND sector_actividad_id = '${p.sector}'`);
  const filterClause = filters.join(" ");

  // Tile envelope inlined as a literal expression on BOTH sides of the
  // pipeline so PostgreSQL can constant-fold at plan time. An earlier
  // version computed the envelope inside a CTE (bounds_3857 +
  // bounds_4326) which the planner treated as a runtime parameter ($1),
  // forcing a Bitmap Index Scan on idx_estab_geom that returned 3.6M
  // rows before applying the entidad/sector filters in heap recheck —
  // 60s per tile under the seeded entidad=09+sector=62 default. Inlining
  // lets the planner pick BitmapAnd(idx_estab_sector, idx_estab_entidad)
  // first (147ms) and only recheck the bbox in the heap. ~200x speedup.
  //
  // The prefilter `geom && ST_Transform(env, 4326)` MUST be SRID-aligned
  // or PostGIS compares raw bbox numbers and finds nothing (Web Mercator
  // coords are 1e6+, lat/lon ~180).
  //
  // ST_TileEnvelope is IMMUTABLE so duplicate calls fold to a single
  // constant during planning; no runtime cost from repeating it.
  const tileEnv3857 = `ST_TileEnvelope(${p.z}, ${p.x}, ${p.y})`;
  // LIMIT without ORDER BY — the planner short-circuits the scan as soon
  // as TILE_FEATURE_CAP matching rows are found, so an unfiltered low-
  // zoom tile completes in ~400ms instead of 16s. The trade-off is that
  // the sample is non-uniform (whatever the scan encounters first,
  // typically biased by physical row order which loosely correlates
  // with insert order = state). For density-heatmap visualization at
  // country zoom that's invisible; per-establishment markers at high
  // zoom never hit the cap because the bbox is small enough that all
  // matching rows fit. This is what enables the unfiltered "first
  // visit" experience to be fast without forcing default filters.
  const sql =
    `WITH filtered AS (` +
    `  SELECT clee, nombre, clase_actividad, geom` +
    `  FROM establecimientos` +
    `  WHERE 1=1 ${filterClause}` +
    `    AND geom && ST_Transform(${tileEnv3857}, 4326)` +
    `  LIMIT ${TILE_FEATURE_CAP}` +
    `), mvt_geom AS (` +
    `  SELECT ST_AsMVTGeom(ST_Transform(f.geom, 3857), ${tileEnv3857}, 4096, 64, true) AS geom,` +
    `         f.clee, f.nombre, f.clase_actividad` +
    `  FROM filtered f` +
    `) SELECT encode(ST_AsMVT(mvt_geom, 'establecimientos'), 'base64') FROM mvt_geom;`;

  let stdout: string;
  try {
    const result = await execFileAsync(
      "docker",
      [
        "exec",
        config.dbContainer,
        "psql",
        "-U",
        "postgres",
        "-d",
        "postgres",
        "-t",
        "-A",
        "-c",
        sql,
      ],
      { encoding: "utf-8", timeout: 30_000, maxBuffer: 50 * 1024 * 1024 },
    );
    stdout = result.stdout.trim();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new HttpError(`tile generation failed: ${msg}`, 502, "postgis.error");
  }

  if (!stdout) {
    // Empty tile is valid — return a zero-byte MVT (empty layer).
    return new ArrayBuffer(0);
  }
  const buf = Buffer.from(stdout, "base64");
  // Slice off the parent ArrayBuffer to detach from any pooled storage and
  // give Response a clean BodyInit-compatible value.
  return buf.buffer.slice(
    buf.byteOffset,
    buf.byteOffset + buf.byteLength,
  ) as ArrayBuffer;
}
