/**
 * GET /tiles/:z/:x/:y.mvt — Mapbox Vector Tile endpoint for the analyzer map.
 *
 * Returns a binary MVT (application/x-protobuf) generated by PostGIS
 * ST_AsMVT directly — no pg_tileserv, no extra runtime dependency.
 *
 * Optional query filters:
 *  - entidad — 2-digit clave (01-32)
 *  - sector  — 2-digit SCIAN derived from SUBSTR(clee, 6, 2)
 *
 * Hard cap: TILE_FEATURE_CAP features per tile. Above that we sample
 * deterministically by ORDER BY clee LIMIT cap (clee has unique index,
 * so the cost is dominated by the bbox filter, not the sort).
 *
 * Auth: X-Api-Key (mounted in server.ts). Rate limit: 5 req/sec/IP
 * (mounted in server.ts via makeRateLimitMiddleware).
 *
 * SQL composition is safe: every interpolated value is either a number
 * (parsed + bounded by Number.isInteger checks) or a 2-char regex-validated
 * string. There is no path for user input to reach SQL unparsed.
 */

import { execFileSync } from "node:child_process";
import type { Context } from "hono";
import { HttpError } from "../middleware/error.js";
import {
  ENTIDAD_RE,
  MAX_TILE_ZOOM,
  SCIAN_RE,
  TILE_FEATURE_CAP,
  type ApiServerConfig,
} from "../types.js";

const TILE_CACHE_SECONDS = 3600;

export async function tilesHandler(
  c: Context,
  config: ApiServerConfig,
): Promise<Response> {
  const z = parseTileCoord(c.req.param("z"), "z", MAX_TILE_ZOOM);
  const x = parseTileCoord(c.req.param("x"), "x", 2 ** z - 1);
  const y = parseTileCoord(c.req.param("y"), "y", 2 ** z - 1);

  const entidad = c.req.query("entidad");
  if (entidad !== undefined && !ENTIDAD_RE.test(entidad)) {
    throw new HttpError(
      `entidad inválida "${entidad}"`,
      400,
      "validation.entidad",
    );
  }
  const sector = c.req.query("sector");
  if (sector !== undefined && !SCIAN_RE.test(sector)) {
    throw new HttpError(
      `sector inválido "${sector}"`,
      400,
      "validation.sector",
    );
  }

  const mvt = await buildTile(config, {
    z,
    x,
    y,
    ...(entidad !== undefined ? { entidad } : {}),
    ...(sector !== undefined ? { sector } : {}),
  });

  return new Response(mvt, {
    status: 200,
    headers: {
      "content-type": "application/x-protobuf",
      "cache-control": `public, max-age=${TILE_CACHE_SECONDS}`,
      // Vary on the auth header so a downstream shared cache never serves
      // a tile from one API key to another.
      vary: "X-Api-Key",
      "x-tile-bytes": String(mvt.byteLength),
    },
  });
}

function parseTileCoord(
  raw: string | undefined,
  name: string,
  maxInclusive: number,
): number {
  if (raw === undefined || raw === "") {
    throw new HttpError(`tile ${name} faltante`, 400, "validation.tile");
  }
  // y may have a `.mvt` suffix from the route param; strip it.
  const cleaned = name === "y" ? raw.replace(/\.mvt$/, "") : raw;
  const n = Number(cleaned);
  if (
    !Number.isInteger(n) ||
    n < 0 ||
    n > maxInclusive ||
    !/^[0-9]+$/.test(cleaned)
  ) {
    throw new HttpError(
      `tile ${name} inválido "${raw}" — debe ser entero 0..${maxInclusive}`,
      400,
      "validation.tile",
    );
  }
  return n;
}

interface TileParams {
  z: number;
  x: number;
  y: number;
  entidad?: string;
  sector?: string;
}

async function buildTile(
  config: ApiServerConfig,
  p: TileParams,
): Promise<ArrayBuffer> {
  // Compose the WHERE additively so the SQL stays simple. All interpolations
  // are pre-validated integers or regex-bounded 2-char strings.
  const filters: string[] = [];
  if (p.entidad) filters.push(`AND entidad = '${p.entidad}'`);
  if (p.sector) filters.push(`AND SUBSTR(clee, 6, 2) = '${p.sector}'`);
  const filterClause = filters.join(" ");

  // bounds_3857 is the tile envelope in Web Mercator (3857) — used by
  // ST_AsMVTGeom which requires the same SRID as the tile.
  // bounds_4326 is the same envelope reprojected to lat/lon — used by the
  // bbox prefilter `&&` against establecimientos.geom (SRID 4326). The
  // prefilter MUST be SRID-aligned or PostGIS compares raw bbox numbers
  // and finds nothing (Web Mercator coords are 1e6+, lat/lon ~180).
  const sql =
    `WITH bounds_3857 AS (` +
    `  SELECT ST_TileEnvelope(${p.z}, ${p.x}, ${p.y}) AS geom` +
    `), bounds_4326 AS (` +
    `  SELECT ST_Transform(geom, 4326) AS geom FROM bounds_3857` +
    `), filtered AS (` +
    `  SELECT clee, nombre, clase_actividad, geom` +
    `  FROM establecimientos` +
    `  WHERE geom && (SELECT geom FROM bounds_4326)` +
    `  ${filterClause}` +
    // hashtext gives a deterministic but uniform-distribution sample —
    // ORDER BY clee would systematically over-represent low-numbered entidades.
    `  ORDER BY hashtext(clee)` +
    `  LIMIT ${TILE_FEATURE_CAP}` +
    `), mvt_geom AS (` +
    `  SELECT ST_AsMVTGeom(ST_Transform(f.geom, 3857), b.geom, 4096, 64, true) AS geom,` +
    `         f.clee, f.nombre, f.clase_actividad` +
    `  FROM filtered f, bounds_3857 b` +
    `) SELECT encode(ST_AsMVT(mvt_geom, 'establecimientos'), 'base64') FROM mvt_geom;`;

  let stdout: string;
  try {
    stdout = execFileSync(
      "docker",
      [
        "exec",
        config.dbContainer,
        "psql",
        "-U",
        "postgres",
        "-d",
        "postgres",
        "-t",
        "-A",
        "-c",
        sql,
      ],
      { encoding: "utf-8", timeout: 30_000, maxBuffer: 50 * 1024 * 1024 },
    ).trim();
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    throw new HttpError(`tile generation failed: ${msg}`, 502, "postgis.error");
  }

  if (!stdout) {
    // Empty tile is valid — return a zero-byte MVT (empty layer).
    return new ArrayBuffer(0);
  }
  const buf = Buffer.from(stdout, "base64");
  // Slice off the parent ArrayBuffer to detach from any pooled storage and
  // give Response a clean BodyInit-compatible value.
  return buf.buffer.slice(
    buf.byteOffset,
    buf.byteOffset + buf.byteLength,
  ) as ArrayBuffer;
}
