-- EIC 2025 (INEGI Encuesta Intercensal 2025) municipal views over
-- eic_2025_municipio_raw. Canonical DDL: scripts/load-eic2025.ts drops the
-- three views explicitly, swaps the raw table in and re-runs this file inside
-- its single load transaction (docs/EIC-2025-LOADER-BRIEF-2026-09-28.md §4).
--
-- Rules for this file (scripts/load-eic2025.test.ts pins them):
--   * No BEGIN/COMMIT and no psql meta-commands: it runs inside the loader's
--     transaction, piped over stdin.
--   * The views read ONLY eic_2025_municipio_raw (and each other). They must
--     never depend on the 2025 municipio universe view, the 2020 -> 2025
--     bridge table or any Censo 2020 relation: the Censo loader drops those
--     without CASCADE, so a dependent view here would break every Censo
--     reload. Join them in the handlers instead.
--   * Estimates come from a sample survey of private dwellings: POBTOT is
--     "Población en viviendas particulares habitadas", not the census total.
--
-- Municipio rows: cve_loc = '0000' AND mun NOT IN ('000', '997') (2,478
-- units). NOM_MUN suffixes: '*' = fully enumerated municipio (750), '**' =
-- sample too small, most indicators 'MI' (7). Sentinels 'MI' (insufficient
-- sample) and 'NA' (zero denominator) become NULL; any other non-numeric
-- value fails the cast and rolls the load back.

-- eic_2025_municipio: the 'Valor' estimator, one row per municipio.
CREATE OR REPLACE VIEW eic_2025_municipio AS
SELECT
  r.cve_mun,
  r.cve_ent,
  r.mun,
  r.cvegeo,
  r.nom_ent,
  regexp_replace(r.nom_mun, '\*+$', '') AS nom_mun,
  (r.nom_mun ~ '(^|[^*])\*$') AS enumeracion_completa,
  (r.nom_mun ~ '\*\*$') AS muestra_insuficiente,
  NULLIF(NULLIF(NULLIF(r.pobtot, ''), 'MI'), 'NA')::numeric AS pobtot,
  NULLIF(NULLIF(NULLIF(r.pobfem, ''), 'MI'), 'NA')::numeric AS pobfem,
  NULLIF(NULLIF(NULLIF(r.pobmas, ''), 'MI'), 'NA')::numeric AS pobmas,
  NULLIF(NULLIF(NULLIF(r.p_3ymas, ''), 'MI'), 'NA')::numeric AS p_3ymas,
  NULLIF(NULLIF(NULLIF(r.p_3ymas_f, ''), 'MI'), 'NA')::numeric AS p_3ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_3ymas_m, ''), 'MI'), 'NA')::numeric AS p_3ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_5ymas, ''), 'MI'), 'NA')::numeric AS p_5ymas,
  NULLIF(NULLIF(NULLIF(r.p_5ymas_f, ''), 'MI'), 'NA')::numeric AS p_5ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_5ymas_m, ''), 'MI'), 'NA')::numeric AS p_5ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_12ymas, ''), 'MI'), 'NA')::numeric AS p_12ymas,
  NULLIF(NULLIF(NULLIF(r.p_12ymas_f, ''), 'MI'), 'NA')::numeric AS p_12ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_12ymas_m, ''), 'MI'), 'NA')::numeric AS p_12ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_15ymas, ''), 'MI'), 'NA')::numeric AS p_15ymas,
  NULLIF(NULLIF(NULLIF(r.p_15ymas_f, ''), 'MI'), 'NA')::numeric AS p_15ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_15ymas_m, ''), 'MI'), 'NA')::numeric AS p_15ymas_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_0a4, ''), 'MI'), 'NA')::numeric AS pcn_p_0a4,
  NULLIF(NULLIF(NULLIF(r.pcn_p_0a4_f, ''), 'MI'), 'NA')::numeric AS pcn_p_0a4_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_0a4_m, ''), 'MI'), 'NA')::numeric AS pcn_p_0a4_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_5a9, ''), 'MI'), 'NA')::numeric AS pcn_p_5a9,
  NULLIF(NULLIF(NULLIF(r.pcn_p_5a9_f, ''), 'MI'), 'NA')::numeric AS pcn_p_5a9_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_5a9_m, ''), 'MI'), 'NA')::numeric AS pcn_p_5a9_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_10a14, ''), 'MI'), 'NA')::numeric AS pcn_p_10a14,
  NULLIF(NULLIF(NULLIF(r.pcn_p_10a14_f, ''), 'MI'), 'NA')::numeric AS pcn_p_10a14_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_10a14_m, ''), 'MI'), 'NA')::numeric AS pcn_p_10a14_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_15a19, ''), 'MI'), 'NA')::numeric AS pcn_p_15a19,
  NULLIF(NULLIF(NULLIF(r.pcn_p_15a19_f, ''), 'MI'), 'NA')::numeric AS pcn_p_15a19_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_15a19_m, ''), 'MI'), 'NA')::numeric AS pcn_p_15a19_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_20a24, ''), 'MI'), 'NA')::numeric AS pcn_p_20a24,
  NULLIF(NULLIF(NULLIF(r.pcn_p_20a24_f, ''), 'MI'), 'NA')::numeric AS pcn_p_20a24_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_20a24_m, ''), 'MI'), 'NA')::numeric AS pcn_p_20a24_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_25a29, ''), 'MI'), 'NA')::numeric AS pcn_p_25a29,
  NULLIF(NULLIF(NULLIF(r.pcn_p_25a29_f, ''), 'MI'), 'NA')::numeric AS pcn_p_25a29_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_25a29_m, ''), 'MI'), 'NA')::numeric AS pcn_p_25a29_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_30a34, ''), 'MI'), 'NA')::numeric AS pcn_p_30a34,
  NULLIF(NULLIF(NULLIF(r.pcn_p_30a34_f, ''), 'MI'), 'NA')::numeric AS pcn_p_30a34_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_30a34_m, ''), 'MI'), 'NA')::numeric AS pcn_p_30a34_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_35a39, ''), 'MI'), 'NA')::numeric AS pcn_p_35a39,
  NULLIF(NULLIF(NULLIF(r.pcn_p_35a39_f, ''), 'MI'), 'NA')::numeric AS pcn_p_35a39_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_35a39_m, ''), 'MI'), 'NA')::numeric AS pcn_p_35a39_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_40a44, ''), 'MI'), 'NA')::numeric AS pcn_p_40a44,
  NULLIF(NULLIF(NULLIF(r.pcn_p_40a44_f, ''), 'MI'), 'NA')::numeric AS pcn_p_40a44_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_40a44_m, ''), 'MI'), 'NA')::numeric AS pcn_p_40a44_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_45a49, ''), 'MI'), 'NA')::numeric AS pcn_p_45a49,
  NULLIF(NULLIF(NULLIF(r.pcn_p_45a49_f, ''), 'MI'), 'NA')::numeric AS pcn_p_45a49_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_45a49_m, ''), 'MI'), 'NA')::numeric AS pcn_p_45a49_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_50a54, ''), 'MI'), 'NA')::numeric AS pcn_p_50a54,
  NULLIF(NULLIF(NULLIF(r.pcn_p_50a54_f, ''), 'MI'), 'NA')::numeric AS pcn_p_50a54_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_50a54_m, ''), 'MI'), 'NA')::numeric AS pcn_p_50a54_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_55a59, ''), 'MI'), 'NA')::numeric AS pcn_p_55a59,
  NULLIF(NULLIF(NULLIF(r.pcn_p_55a59_f, ''), 'MI'), 'NA')::numeric AS pcn_p_55a59_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_55a59_m, ''), 'MI'), 'NA')::numeric AS pcn_p_55a59_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_60a64, ''), 'MI'), 'NA')::numeric AS pcn_p_60a64,
  NULLIF(NULLIF(NULLIF(r.pcn_p_60a64_f, ''), 'MI'), 'NA')::numeric AS pcn_p_60a64_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_60a64_m, ''), 'MI'), 'NA')::numeric AS pcn_p_60a64_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_65a69, ''), 'MI'), 'NA')::numeric AS pcn_p_65a69,
  NULLIF(NULLIF(NULLIF(r.pcn_p_65a69_f, ''), 'MI'), 'NA')::numeric AS pcn_p_65a69_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_65a69_m, ''), 'MI'), 'NA')::numeric AS pcn_p_65a69_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_70a74, ''), 'MI'), 'NA')::numeric AS pcn_p_70a74,
  NULLIF(NULLIF(NULLIF(r.pcn_p_70a74_f, ''), 'MI'), 'NA')::numeric AS pcn_p_70a74_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_70a74_m, ''), 'MI'), 'NA')::numeric AS pcn_p_70a74_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_75ymas, ''), 'MI'), 'NA')::numeric AS pcn_p_75ymas,
  NULLIF(NULLIF(NULLIF(r.pcn_p_75ymas_f, ''), 'MI'), 'NA')::numeric AS pcn_p_75ymas_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_75ymas_m, ''), 'MI'), 'NA')::numeric AS pcn_p_75ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_6a14, ''), 'MI'), 'NA')::numeric AS p_6a14,
  NULLIF(NULLIF(NULLIF(r.p_6a14_f, ''), 'MI'), 'NA')::numeric AS p_6a14_f,
  NULLIF(NULLIF(NULLIF(r.p_6a14_m, ''), 'MI'), 'NA')::numeric AS p_6a14_m,
  NULLIF(NULLIF(NULLIF(r.pob0_14, ''), 'MI'), 'NA')::numeric AS pob0_14,
  NULLIF(NULLIF(NULLIF(r.pob0_14_f, ''), 'MI'), 'NA')::numeric AS pob0_14_f,
  NULLIF(NULLIF(NULLIF(r.pob0_14_m, ''), 'MI'), 'NA')::numeric AS pob0_14_m,
  NULLIF(NULLIF(NULLIF(r.pob15_64, ''), 'MI'), 'NA')::numeric AS pob15_64,
  NULLIF(NULLIF(NULLIF(r.pob65_mas, ''), 'MI'), 'NA')::numeric AS pob65_mas,
  NULLIF(NULLIF(NULLIF(r.p_15a49_f, ''), 'MI'), 'NA')::numeric AS p_15a49_f,
  NULLIF(NULLIF(NULLIF(r.rel_h_m, ''), 'MI'), 'NA')::numeric AS rel_h_m,
  NULLIF(NULLIF(NULLIF(r.mediana_pobtot, ''), 'MI'), 'NA')::numeric AS mediana_pobtot,
  NULLIF(NULLIF(NULLIF(r.mediana_f, ''), 'MI'), 'NA')::numeric AS mediana_f,
  NULLIF(NULLIF(NULLIF(r.mediana_m, ''), 'MI'), 'NA')::numeric AS mediana_m,
  NULLIF(NULLIF(NULLIF(r.indice_env, ''), 'MI'), 'NA')::numeric AS indice_env,
  NULLIF(NULLIF(NULLIF(r.indice_env_f, ''), 'MI'), 'NA')::numeric AS indice_env_f,
  NULLIF(NULLIF(NULLIF(r.indice_env_m, ''), 'MI'), 'NA')::numeric AS indice_env_m,
  NULLIF(NULLIF(NULLIF(r.razon_dep_tot, ''), 'MI'), 'NA')::numeric AS razon_dep_tot,
  NULLIF(NULLIF(NULLIF(r.razon_dep_inf, ''), 'MI'), 'NA')::numeric AS razon_dep_inf,
  NULLIF(NULLIF(NULLIF(r.razon_dep_vej, ''), 'MI'), 'NA')::numeric AS razon_dep_vej,
  NULLIF(NULLIF(NULLIF(r.prom_hnv, ''), 'MI'), 'NA')::numeric AS prom_hnv,
  NULLIF(NULLIF(NULLIF(r.tgf, ''), 'MI'), 'NA')::numeric AS tgf,
  NULLIF(NULLIF(NULLIF(r.pcn_hf, ''), 'MI'), 'NA')::numeric AS pcn_hf,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacent, ''), 'MI'), 'NA')::numeric AS pcn_pnacent,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacent_f, ''), 'MI'), 'NA')::numeric AS pcn_pnacent_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacent_m, ''), 'MI'), 'NA')::numeric AS pcn_pnacent_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacoe, ''), 'MI'), 'NA')::numeric AS pcn_pnacoe,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacoe_f, ''), 'MI'), 'NA')::numeric AS pcn_pnacoe_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacoe_m, ''), 'MI'), 'NA')::numeric AS pcn_pnacoe_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop, ''), 'MI'), 'NA')::numeric AS pcn_pnacop,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_f, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_m, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_m,
  NULLIF(NULLIF(NULLIF(r.pnacop, ''), 'MI'), 'NA')::numeric AS pnacop,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_nac, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_nac,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_nonac, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_nonac,
  NULLIF(NULLIF(NULLIF(r.pcn_presm20, ''), 'MI'), 'NA')::numeric AS pcn_presm20,
  NULLIF(NULLIF(NULLIF(r.pcn_presom20, ''), 'MI'), 'NA')::numeric AS pcn_presom20,
  NULLIF(NULLIF(NULLIF(r.pcn_prese20, ''), 'MI'), 'NA')::numeric AS pcn_prese20,
  NULLIF(NULLIF(NULLIF(r.pcn_presoe20, ''), 'MI'), 'NA')::numeric AS pcn_presoe20,
  NULLIF(NULLIF(NULLIF(r.pcn_preseua20, ''), 'MI'), 'NA')::numeric AS pcn_preseua20,
  NULLIF(NULLIF(NULLIF(r.pcn_presop20, ''), 'MI'), 'NA')::numeric AS pcn_presop20,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_ind, ''), 'MI'), 'NA')::numeric AS pcn_pob_ind,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_ind_f, ''), 'MI'), 'NA')::numeric AS pcn_pob_ind_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_ind_m, ''), 'MI'), 'NA')::numeric AS pcn_pob_ind_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_hli, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_hli,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_hli_f, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_hli_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_hli_m, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_hli_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hlinhe, ''), 'MI'), 'NA')::numeric AS pcn_p3hlinhe,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hlinhe_f, ''), 'MI'), 'NA')::numeric AS pcn_p3hlinhe_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hlinhe_m, ''), 'MI'), 'NA')::numeric AS pcn_p3hlinhe_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hli_he, ''), 'MI'), 'NA')::numeric AS pcn_p3hli_he,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hli_he_f, ''), 'MI'), 'NA')::numeric AS pcn_p3hli_he_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hli_he_m, ''), 'MI'), 'NA')::numeric AS pcn_p3hli_he_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3nhli_cli, ''), 'MI'), 'NA')::numeric AS pcn_p3nhli_cli,
  NULLIF(NULLIF(NULLIF(r.hog_ind, ''), 'MI'), 'NA')::numeric AS hog_ind,
  NULLIF(NULLIF(NULLIF(r.phog_ind, ''), 'MI'), 'NA')::numeric AS phog_ind,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_afro, ''), 'MI'), 'NA')::numeric AS pcn_pob_afro,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_afro_f, ''), 'MI'), 'NA')::numeric AS pcn_pob_afro_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_afro_m, ''), 'MI'), 'NA')::numeric AS pcn_pob_afro_m,
  NULLIF(NULLIF(NULLIF(r.hog_afro, ''), 'MI'), 'NA')::numeric AS hog_afro,
  NULLIF(NULLIF(NULLIF(r.phog_afro, ''), 'MI'), 'NA')::numeric AS phog_afro,
  NULLIF(NULLIF(NULLIF(r.pcon_disc, ''), 'MI'), 'NA')::numeric AS pcon_disc,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc_f, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc_m, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc0a14, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc0a14,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc15a29, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc15a29,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc30a59, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc30a59,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc60ym, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc60ym,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_vis, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_vis,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_aud, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_aud,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_mot, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_mot,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_men, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_men,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_mot2, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_mot2,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_leng, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_leng,
  NULLIF(NULLIF(NULLIF(r.pcon_limi, ''), 'MI'), 'NA')::numeric AS pcon_limi,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_vis, ''), 'MI'), 'NA')::numeric AS pcn_pclim_vis,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_oaud, ''), 'MI'), 'NA')::numeric AS pcn_pclim_oaud,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_csb, ''), 'MI'), 'NA')::numeric AS pcn_pclim_csb,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_re_co, ''), 'MI'), 'NA')::numeric AS pcn_pclim_re_co,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_mot2, ''), 'MI'), 'NA')::numeric AS pcn_pclim_mot2,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_haco, ''), 'MI'), 'NA')::numeric AS pcn_pclim_haco,
  NULLIF(NULLIF(NULLIF(r.pclim_pmen, ''), 'MI'), 'NA')::numeric AS pclim_pmen,
  NULLIF(NULLIF(NULLIF(r.psind_lim, ''), 'MI'), 'NA')::numeric AS psind_lim,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_asis, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_asis,
  NULLIF(NULLIF(NULLIF(r.pcn_p6a14_noa, ''), 'MI'), 'NA')::numeric AS pcn_p6a14_noa,
  NULLIF(NULLIF(NULLIF(r.pcn_p6a14_noa_f, ''), 'MI'), 'NA')::numeric AS pcn_p6a14_noa_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p6a14_noa_m, ''), 'MI'), 'NA')::numeric AS pcn_p6a14_noa_m,
  NULLIF(NULLIF(NULLIF(r.pnc_p6a14an, ''), 'MI'), 'NA')::numeric AS pnc_p6a14an,
  NULLIF(NULLIF(NULLIF(r.pnc_p6a14an_f, ''), 'MI'), 'NA')::numeric AS pnc_p6a14an_f,
  NULLIF(NULLIF(NULLIF(r.pnc_p6a14an_m, ''), 'MI'), 'NA')::numeric AS pnc_p6a14an_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_an, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_an,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_an_f, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_an_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_an_m, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_an_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_se, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_se,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_eb, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_eb,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_ems, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_ems,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_es, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_es,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_pos, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_pos,
  NULLIF(NULLIF(NULLIF(r.graproes, ''), 'MI'), 'NA')::numeric AS graproes,
  NULLIF(NULLIF(NULLIF(r.graproes_f, ''), 'MI'), 'NA')::numeric AS graproes_f,
  NULLIF(NULLIF(NULLIF(r.graproes_m, ''), 'MI'), 'NA')::numeric AS graproes_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pea, ''), 'MI'), 'NA')::numeric AS pcn_pea,
  NULLIF(NULLIF(NULLIF(r.pcn_pea_f, ''), 'MI'), 'NA')::numeric AS pcn_pea_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pea_m, ''), 'MI'), 'NA')::numeric AS pcn_pea_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pe_inac, ''), 'MI'), 'NA')::numeric AS pcn_pe_inac,
  NULLIF(NULLIF(NULLIF(r.pcn_pe_inac_f, ''), 'MI'), 'NA')::numeric AS pcn_pe_inac_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pe_inac_m, ''), 'MI'), 'NA')::numeric AS pcn_pe_inac_m,
  NULLIF(NULLIF(NULLIF(r.pocupada, ''), 'MI'), 'NA')::numeric AS pocupada,
  NULLIF(NULLIF(NULLIF(r.pcn_pocupada, ''), 'MI'), 'NA')::numeric AS pcn_pocupada,
  NULLIF(NULLIF(NULLIF(r.pcn_pocupada_f, ''), 'MI'), 'NA')::numeric AS pcn_pocupada_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pocupada_m, ''), 'MI'), 'NA')::numeric AS pcn_pocupada_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pdesocup, ''), 'MI'), 'NA')::numeric AS pcn_pdesocup,
  NULLIF(NULLIF(NULLIF(r.pcn_pdesocup_f, ''), 'MI'), 'NA')::numeric AS pcn_pdesocup_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pdesocup_m, ''), 'MI'), 'NA')::numeric AS pcn_pdesocup_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_asa, ''), 'MI'), 'NA')::numeric AS pcn_pocup_asa,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_emp, ''), 'MI'), 'NA')::numeric AS pcn_pocup_emp,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_cpro, ''), 'MI'), 'NA')::numeric AS pcn_pocup_cpro,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_spag, ''), 'MI'), 'NA')::numeric AS pcn_pocup_spag,
  NULLIF(NULLIF(NULLIF(r.pder_ss, ''), 'MI'), 'NA')::numeric AS pder_ss,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_ss, ''), 'MI'), 'NA')::numeric AS pcn_pder_ss,
  NULLIF(NULLIF(NULLIF(r.pcn_psinder, ''), 'MI'), 'NA')::numeric AS pcn_psinder,
  NULLIF(NULLIF(NULLIF(r.pcn_pcssyrecac, ''), 'MI'), 'NA')::numeric AS pcn_pcssyrecac,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_imss, ''), 'MI'), 'NA')::numeric AS pcn_pder_imss,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_iste, ''), 'MI'), 'NA')::numeric AS pcn_pder_iste,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_pdom, ''), 'MI'), 'NA')::numeric AS pcn_pafil_pdom,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_imssb, ''), 'MI'), 'NA')::numeric AS pcn_pder_imssb,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_ipub, ''), 'MI'), 'NA')::numeric AS pcn_pafil_ipub,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_ipriv, ''), 'MI'), 'NA')::numeric AS pcn_pafil_ipriv,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_otrai, ''), 'MI'), 'NA')::numeric AS pcn_pafil_otrai,
  NULLIF(NULLIF(NULLIF(r.pusu_ss, ''), 'MI'), 'NA')::numeric AS pusu_ss,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_imss, ''), 'MI'), 'NA')::numeric AS pcn_pusu_imss,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_iste, ''), 'MI'), 'NA')::numeric AS pcn_pusu_iste,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_pdom, ''), 'MI'), 'NA')::numeric AS pcn_pusu_pdom,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_imssb, ''), 'MI'), 'NA')::numeric AS pcn_pusu_imssb,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_ipub, ''), 'MI'), 'NA')::numeric AS pcn_pusu_ipub,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_ipriv, ''), 'MI'), 'NA')::numeric AS pcn_pusu_ipriv,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_cfarm, ''), 'MI'), 'NA')::numeric AS pcn_pusu_cfarm,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_otrai, ''), 'MI'), 'NA')::numeric AS pcn_pusu_otrai,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_ent, ''), 'MI'), 'NA')::numeric AS pcn_pasis_ent,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_oent, ''), 'MI'), 'NA')::numeric AS pcn_pasis_oent,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_15min, ''), 'MI'), 'NA')::numeric AS pcn_pasis_15min,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_30min, ''), 'MI'), 'NA')::numeric AS pcn_pasis_30min,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_1hor, ''), 'MI'), 'NA')::numeric AS pcn_pasis_1hor,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_1hym, ''), 'MI'), 'NA')::numeric AS pcn_pasis_1hym,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_cam, ''), 'MI'), 'NA')::numeric AS pcn_pasis_cam,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_bici, ''), 'MI'), 'NA')::numeric AS pcn_pasis_bici,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_met, ''), 'MI'), 'NA')::numeric AS pcn_pasis_met,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_trol, ''), 'MI'), 'NA')::numeric AS pcn_pasis_trol,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_tesc, ''), 'MI'), 'NA')::numeric AS pcn_pasis_tesc,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_taxi, ''), 'MI'), 'NA')::numeric AS pcn_pasis_taxi,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_moto, ''), 'MI'), 'NA')::numeric AS pcn_pasis_moto,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_auto, ''), 'MI'), 'NA')::numeric AS pcn_pasis_auto,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_omed, ''), 'MI'), 'NA')::numeric AS pcn_pasis_omed,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_ent, ''), 'MI'), 'NA')::numeric AS pcn_pocup_ent,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_oent, ''), 'MI'), 'NA')::numeric AS pcn_pocup_oent,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_15min, ''), 'MI'), 'NA')::numeric AS pcn_pocup_15min,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_30min, ''), 'MI'), 'NA')::numeric AS pcn_pocup_30min,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_1hor, ''), 'MI'), 'NA')::numeric AS pcn_pocup_1hor,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_2hor, ''), 'MI'), 'NA')::numeric AS pcn_pocup_2hor,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_2hym, ''), 'MI'), 'NA')::numeric AS pcn_pocup_2hym,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_cam, ''), 'MI'), 'NA')::numeric AS pcn_pocup_cam,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_bici, ''), 'MI'), 'NA')::numeric AS pcn_pocup_bici,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_met, ''), 'MI'), 'NA')::numeric AS pcn_pocup_met,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_trol, ''), 'MI'), 'NA')::numeric AS pcn_pocup_trol,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_tper, ''), 'MI'), 'NA')::numeric AS pcn_pocup_tper,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_taxi, ''), 'MI'), 'NA')::numeric AS pcn_pocup_taxi,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_moto, ''), 'MI'), 'NA')::numeric AS pcn_pocup_moto,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_auto, ''), 'MI'), 'NA')::numeric AS pcn_pocup_auto,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_omed, ''), 'MI'), 'NA')::numeric AS pcn_pocup_omed,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_solt, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_solt,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_solt_f, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_solt_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_solt_m, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_solt_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_cul, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_cul,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_cul_f, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_cul_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_cul_m, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_cul_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_sepa, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_sepa,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_sepa_f, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_sepa_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_sepa_m, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_sepa_m,
  NULLIF(NULLIF(NULLIF(r.tothog, ''), 'MI'), 'NA')::numeric AS tothog,
  NULLIF(NULLIF(NULLIF(r.hogjef_f, ''), 'MI'), 'NA')::numeric AS hogjef_f,
  NULLIF(NULLIF(NULLIF(r.hogjef_m, ''), 'MI'), 'NA')::numeric AS hogjef_m,
  NULLIF(NULLIF(NULLIF(r.pobhog, ''), 'MI'), 'NA')::numeric AS pobhog,
  NULLIF(NULLIF(NULLIF(r.phogjef_f, ''), 'MI'), 'NA')::numeric AS phogjef_f,
  NULLIF(NULLIF(NULLIF(r.phogjef_m, ''), 'MI'), 'NA')::numeric AS phogjef_m,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_fam, ''), 'MI'), 'NA')::numeric AS pcn_hog_fam,
  NULLIF(NULLIF(NULLIF(r.pcn_pobhog_fam, ''), 'MI'), 'NA')::numeric AS pcn_pobhog_fam,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_nfam, ''), 'MI'), 'NA')::numeric AS pcn_hog_nfam,
  NULLIF(NULLIF(NULLIF(r.pcn_pobhog_nfam, ''), 'MI'), 'NA')::numeric AS pcn_pobhog_nfam,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_perc, ''), 'MI'), 'NA')::numeric AS pcn_hog_perc,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_nperc, ''), 'MI'), 'NA')::numeric AS pcn_hog_nperc,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_gob, ''), 'MI'), 'NA')::numeric AS pcn_hog_gob,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_jub, ''), 'MI'), 'NA')::numeric AS pcn_hog_jub,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_oviv, ''), 'MI'), 'NA')::numeric AS pcn_hog_oviv,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_opais, ''), 'MI'), 'NA')::numeric AS pcn_hog_opais,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_alim_n, ''), 'MI'), 'NA')::numeric AS pcn_hog_alim_n,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_alim, ''), 'MI'), 'NA')::numeric AS pcn_hog_alim,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_adl1, ''), 'MI'), 'NA')::numeric AS pcn_alim_adl1,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_adl2, ''), 'MI'), 'NA')::numeric AS pcn_alim_adl2,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_adl3, ''), 'MI'), 'NA')::numeric AS pcn_alim_adl3,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_adl1, ''), 'MI'), 'NA')::numeric AS pcn_ing_adl1,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_adl2, ''), 'MI'), 'NA')::numeric AS pcn_ing_adl2,
  NULLIF(NULLIF(NULLIF(r.hog_men_alim, ''), 'MI'), 'NA')::numeric AS hog_men_alim,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_men1, ''), 'MI'), 'NA')::numeric AS pcn_alim_men1,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_men2, ''), 'MI'), 'NA')::numeric AS pcn_alim_men2,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_men3, ''), 'MI'), 'NA')::numeric AS pcn_alim_men3,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_men1, ''), 'MI'), 'NA')::numeric AS pcn_ing_men1,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_men2, ''), 'MI'), 'NA')::numeric AS pcn_ing_men2,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_men3, ''), 'MI'), 'NA')::numeric AS pcn_ing_men3,
  NULLIF(NULLIF(NULLIF(r.pcn_desp_inseg, ''), 'MI'), 'NA')::numeric AS pcn_desp_inseg,
  NULLIF(NULLIF(NULLIF(r.pcn_desp_catas, ''), 'MI'), 'NA')::numeric AS pcn_desp_catas,
  NULLIF(NULLIF(NULLIF(r.vivparhab, ''), 'MI'), 'NA')::numeric AS vivparhab,
  NULLIF(NULLIF(NULLIF(r.vivparhab_c, ''), 'MI'), 'NA')::numeric AS vivparhab_c,
  NULLIF(NULLIF(NULLIF(r.ocupvivpar, ''), 'MI'), 'NA')::numeric AS ocupvivpar,
  NULLIF(NULLIF(NULLIF(r.prom_ocup, ''), 'MI'), 'NA')::numeric AS prom_ocup,
  NULLIF(NULLIF(NULLIF(r.pro_ocup_c, ''), 'MI'), 'NA')::numeric AS pro_ocup_c,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_2_5ocu, ''), 'MI'), 'NA')::numeric AS pcn_vph_2_5ocu,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pdesh, ''), 'MI'), 'NA')::numeric AS pcn_vph_pdesh,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pasb, ''), 'MI'), 'NA')::numeric AS pcn_vph_pasb,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pmad, ''), 'MI'), 'NA')::numeric AS pcn_vph_pmad,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_ptab, ''), 'MI'), 'NA')::numeric AS pcn_vph_ptab,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tdesh, ''), 'MI'), 'NA')::numeric AS pcn_vph_tdesh,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tasb, ''), 'MI'), 'NA')::numeric AS pcn_vph_tasb,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tlosa, ''), 'MI'), 'NA')::numeric AS pcn_vph_tlosa,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_totro, ''), 'MI'), 'NA')::numeric AS pcn_vph_totro,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pisoti, ''), 'MI'), 'NA')::numeric AS pcn_vph_pisoti,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pisocem, ''), 'MI'), 'NA')::numeric AS pcn_vph_pisocem,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pisomad, ''), 'MI'), 'NA')::numeric AS pcn_vph_pisomad,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_1cuart, ''), 'MI'), 'NA')::numeric AS pcn_vph_1cuart,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_2cuart, ''), 'MI'), 'NA')::numeric AS pcn_vph_2cuart,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_3ymasc, ''), 'MI'), 'NA')::numeric AS pcn_vph_3ymasc,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_1dor, ''), 'MI'), 'NA')::numeric AS pcn_vph_1dor,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_2ymasd, ''), 'MI'), 'NA')::numeric AS pcn_vph_2ymasd,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cint, ''), 'MI'), 'NA')::numeric AS pcn_vph_cint,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_csep, ''), 'MI'), 'NA')::numeric AS pcn_vph_csep,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cotro, ''), 'MI'), 'NA')::numeric AS pcn_vph_cotro,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_comgas, ''), 'MI'), 'NA')::numeric AS pcn_vph_comgas,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_comele, ''), 'MI'), 'NA')::numeric AS pcn_vph_comele,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_c_elec, ''), 'MI'), 'NA')::numeric AS pcn_vph_c_elec,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_aguadv, ''), 'MI'), 'NA')::numeric AS pcn_vph_aguadv,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_drenaj, ''), 'MI'), 'NA')::numeric AS pcn_vph_drenaj,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_c_serv, ''), 'MI'), 'NA')::numeric AS pcn_vph_c_serv,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_excsa, ''), 'MI'), 'NA')::numeric AS pcn_vph_excsa,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_dsadma, ''), 'MI'), 'NA')::numeric AS pcn_vph_dsadma,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tinaco, ''), 'MI'), 'NA')::numeric AS pcn_vph_tinaco,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cister, ''), 'MI'), 'NA')::numeric AS pcn_vph_cister,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_bomba, ''), 'MI'), 'NA')::numeric AS pcn_vph_bomba,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_rega, ''), 'MI'), 'NA')::numeric AS pcn_vph_rega,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_boiler, ''), 'MI'), 'NA')::numeric AS pcn_vph_boiler,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_solar, ''), 'MI'), 'NA')::numeric AS pcn_vph_solar,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_aire, ''), 'MI'), 'NA')::numeric AS pcn_vph_aire,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_panel, ''), 'MI'), 'NA')::numeric AS pcn_vph_panel,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_organi, ''), 'MI'), 'NA')::numeric AS pcn_vph_organi,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_animal, ''), 'MI'), 'NA')::numeric AS pcn_vph_animal,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_planta, ''), 'MI'), 'NA')::numeric AS pcn_vph_planta,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_vender, ''), 'MI'), 'NA')::numeric AS pcn_vph_vender,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cambasu, ''), 'MI'), 'NA')::numeric AS pcn_vph_cambasu,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cntbasu, ''), 'MI'), 'NA')::numeric AS pcn_vph_cntbasu,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_elimbas, ''), 'MI'), 'NA')::numeric AS pcn_vph_elimbas,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_refri, ''), 'MI'), 'NA')::numeric AS pcn_vph_refri,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_lavad, ''), 'MI'), 'NA')::numeric AS pcn_vph_lavad,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_hmicro, ''), 'MI'), 'NA')::numeric AS pcn_vph_hmicro,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_autom, ''), 'MI'), 'NA')::numeric AS pcn_vph_autom,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_moto, ''), 'MI'), 'NA')::numeric AS pcn_vph_moto,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_bici, ''), 'MI'), 'NA')::numeric AS pcn_vph_bici,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_radio, ''), 'MI'), 'NA')::numeric AS pcn_vph_radio,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tv, ''), 'MI'), 'NA')::numeric AS pcn_vph_tv,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pc, ''), 'MI'), 'NA')::numeric AS pcn_vph_pc,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_telef, ''), 'MI'), 'NA')::numeric AS pcn_vph_telef,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cel, ''), 'MI'), 'NA')::numeric AS pcn_vph_cel,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_inter, ''), 'MI'), 'NA')::numeric AS pcn_vph_inter,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tvp, ''), 'MI'), 'NA')::numeric AS pcn_vph_tvp,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_propia, ''), 'MI'), 'NA')::numeric AS pcn_vph_propia,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_alqui, ''), 'MI'), 'NA')::numeric AS pcn_vph_alqui,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_prest, ''), 'MI'), 'NA')::numeric AS pcn_vph_prest,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_otrasit, ''), 'MI'), 'NA')::numeric AS pcn_vph_otrasit,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_propresi, ''), 'MI'), 'NA')::numeric AS pcn_vph_propresi,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pernores, ''), 'MI'), 'NA')::numeric AS pcn_vph_pernores,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_noescri, ''), 'MI'), 'NA')::numeric AS pcn_vph_noescri,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_escrides, ''), 'MI'), 'NA')::numeric AS pcn_vph_escrides
FROM eic_2025_municipio_raw r
WHERE r.estimador = 'Valor'
  AND r.cve_loc = '0000'
  AND r.mun NOT IN ('000', '997');

-- eic_2025_municipio_moe: the four precision rows per municipio (9,912 =
-- 2,478 x 4), 90 % confidence. medida: se = error estándar, li90 / ls90 =
-- límite inferior / superior de confianza, cv = coeficiente de variación (%).
CREATE OR REPLACE VIEW eic_2025_municipio_moe AS
SELECT
  r.cve_mun,
  r.cve_ent,
  r.mun,
  regexp_replace(r.nom_mun, '\*+$', '') AS nom_mun,
  CASE r.estimador
    WHEN 'Error estándar' THEN 'se'
    WHEN 'Límite inferior de confianza' THEN 'li90'
    WHEN 'Límite superior de confianza' THEN 'ls90'
    WHEN 'Coeficiente de variación' THEN 'cv'
  END AS medida,
  NULLIF(NULLIF(NULLIF(r.pobtot, ''), 'MI'), 'NA')::numeric AS pobtot,
  NULLIF(NULLIF(NULLIF(r.pobfem, ''), 'MI'), 'NA')::numeric AS pobfem,
  NULLIF(NULLIF(NULLIF(r.pobmas, ''), 'MI'), 'NA')::numeric AS pobmas,
  NULLIF(NULLIF(NULLIF(r.p_3ymas, ''), 'MI'), 'NA')::numeric AS p_3ymas,
  NULLIF(NULLIF(NULLIF(r.p_3ymas_f, ''), 'MI'), 'NA')::numeric AS p_3ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_3ymas_m, ''), 'MI'), 'NA')::numeric AS p_3ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_5ymas, ''), 'MI'), 'NA')::numeric AS p_5ymas,
  NULLIF(NULLIF(NULLIF(r.p_5ymas_f, ''), 'MI'), 'NA')::numeric AS p_5ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_5ymas_m, ''), 'MI'), 'NA')::numeric AS p_5ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_12ymas, ''), 'MI'), 'NA')::numeric AS p_12ymas,
  NULLIF(NULLIF(NULLIF(r.p_12ymas_f, ''), 'MI'), 'NA')::numeric AS p_12ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_12ymas_m, ''), 'MI'), 'NA')::numeric AS p_12ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_15ymas, ''), 'MI'), 'NA')::numeric AS p_15ymas,
  NULLIF(NULLIF(NULLIF(r.p_15ymas_f, ''), 'MI'), 'NA')::numeric AS p_15ymas_f,
  NULLIF(NULLIF(NULLIF(r.p_15ymas_m, ''), 'MI'), 'NA')::numeric AS p_15ymas_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_0a4, ''), 'MI'), 'NA')::numeric AS pcn_p_0a4,
  NULLIF(NULLIF(NULLIF(r.pcn_p_0a4_f, ''), 'MI'), 'NA')::numeric AS pcn_p_0a4_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_0a4_m, ''), 'MI'), 'NA')::numeric AS pcn_p_0a4_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_5a9, ''), 'MI'), 'NA')::numeric AS pcn_p_5a9,
  NULLIF(NULLIF(NULLIF(r.pcn_p_5a9_f, ''), 'MI'), 'NA')::numeric AS pcn_p_5a9_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_5a9_m, ''), 'MI'), 'NA')::numeric AS pcn_p_5a9_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_10a14, ''), 'MI'), 'NA')::numeric AS pcn_p_10a14,
  NULLIF(NULLIF(NULLIF(r.pcn_p_10a14_f, ''), 'MI'), 'NA')::numeric AS pcn_p_10a14_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_10a14_m, ''), 'MI'), 'NA')::numeric AS pcn_p_10a14_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_15a19, ''), 'MI'), 'NA')::numeric AS pcn_p_15a19,
  NULLIF(NULLIF(NULLIF(r.pcn_p_15a19_f, ''), 'MI'), 'NA')::numeric AS pcn_p_15a19_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_15a19_m, ''), 'MI'), 'NA')::numeric AS pcn_p_15a19_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_20a24, ''), 'MI'), 'NA')::numeric AS pcn_p_20a24,
  NULLIF(NULLIF(NULLIF(r.pcn_p_20a24_f, ''), 'MI'), 'NA')::numeric AS pcn_p_20a24_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_20a24_m, ''), 'MI'), 'NA')::numeric AS pcn_p_20a24_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_25a29, ''), 'MI'), 'NA')::numeric AS pcn_p_25a29,
  NULLIF(NULLIF(NULLIF(r.pcn_p_25a29_f, ''), 'MI'), 'NA')::numeric AS pcn_p_25a29_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_25a29_m, ''), 'MI'), 'NA')::numeric AS pcn_p_25a29_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_30a34, ''), 'MI'), 'NA')::numeric AS pcn_p_30a34,
  NULLIF(NULLIF(NULLIF(r.pcn_p_30a34_f, ''), 'MI'), 'NA')::numeric AS pcn_p_30a34_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_30a34_m, ''), 'MI'), 'NA')::numeric AS pcn_p_30a34_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_35a39, ''), 'MI'), 'NA')::numeric AS pcn_p_35a39,
  NULLIF(NULLIF(NULLIF(r.pcn_p_35a39_f, ''), 'MI'), 'NA')::numeric AS pcn_p_35a39_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_35a39_m, ''), 'MI'), 'NA')::numeric AS pcn_p_35a39_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_40a44, ''), 'MI'), 'NA')::numeric AS pcn_p_40a44,
  NULLIF(NULLIF(NULLIF(r.pcn_p_40a44_f, ''), 'MI'), 'NA')::numeric AS pcn_p_40a44_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_40a44_m, ''), 'MI'), 'NA')::numeric AS pcn_p_40a44_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_45a49, ''), 'MI'), 'NA')::numeric AS pcn_p_45a49,
  NULLIF(NULLIF(NULLIF(r.pcn_p_45a49_f, ''), 'MI'), 'NA')::numeric AS pcn_p_45a49_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_45a49_m, ''), 'MI'), 'NA')::numeric AS pcn_p_45a49_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_50a54, ''), 'MI'), 'NA')::numeric AS pcn_p_50a54,
  NULLIF(NULLIF(NULLIF(r.pcn_p_50a54_f, ''), 'MI'), 'NA')::numeric AS pcn_p_50a54_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_50a54_m, ''), 'MI'), 'NA')::numeric AS pcn_p_50a54_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_55a59, ''), 'MI'), 'NA')::numeric AS pcn_p_55a59,
  NULLIF(NULLIF(NULLIF(r.pcn_p_55a59_f, ''), 'MI'), 'NA')::numeric AS pcn_p_55a59_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_55a59_m, ''), 'MI'), 'NA')::numeric AS pcn_p_55a59_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_60a64, ''), 'MI'), 'NA')::numeric AS pcn_p_60a64,
  NULLIF(NULLIF(NULLIF(r.pcn_p_60a64_f, ''), 'MI'), 'NA')::numeric AS pcn_p_60a64_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_60a64_m, ''), 'MI'), 'NA')::numeric AS pcn_p_60a64_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_65a69, ''), 'MI'), 'NA')::numeric AS pcn_p_65a69,
  NULLIF(NULLIF(NULLIF(r.pcn_p_65a69_f, ''), 'MI'), 'NA')::numeric AS pcn_p_65a69_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_65a69_m, ''), 'MI'), 'NA')::numeric AS pcn_p_65a69_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_70a74, ''), 'MI'), 'NA')::numeric AS pcn_p_70a74,
  NULLIF(NULLIF(NULLIF(r.pcn_p_70a74_f, ''), 'MI'), 'NA')::numeric AS pcn_p_70a74_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_70a74_m, ''), 'MI'), 'NA')::numeric AS pcn_p_70a74_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p_75ymas, ''), 'MI'), 'NA')::numeric AS pcn_p_75ymas,
  NULLIF(NULLIF(NULLIF(r.pcn_p_75ymas_f, ''), 'MI'), 'NA')::numeric AS pcn_p_75ymas_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p_75ymas_m, ''), 'MI'), 'NA')::numeric AS pcn_p_75ymas_m,
  NULLIF(NULLIF(NULLIF(r.p_6a14, ''), 'MI'), 'NA')::numeric AS p_6a14,
  NULLIF(NULLIF(NULLIF(r.p_6a14_f, ''), 'MI'), 'NA')::numeric AS p_6a14_f,
  NULLIF(NULLIF(NULLIF(r.p_6a14_m, ''), 'MI'), 'NA')::numeric AS p_6a14_m,
  NULLIF(NULLIF(NULLIF(r.pob0_14, ''), 'MI'), 'NA')::numeric AS pob0_14,
  NULLIF(NULLIF(NULLIF(r.pob0_14_f, ''), 'MI'), 'NA')::numeric AS pob0_14_f,
  NULLIF(NULLIF(NULLIF(r.pob0_14_m, ''), 'MI'), 'NA')::numeric AS pob0_14_m,
  NULLIF(NULLIF(NULLIF(r.pob15_64, ''), 'MI'), 'NA')::numeric AS pob15_64,
  NULLIF(NULLIF(NULLIF(r.pob65_mas, ''), 'MI'), 'NA')::numeric AS pob65_mas,
  NULLIF(NULLIF(NULLIF(r.p_15a49_f, ''), 'MI'), 'NA')::numeric AS p_15a49_f,
  NULLIF(NULLIF(NULLIF(r.rel_h_m, ''), 'MI'), 'NA')::numeric AS rel_h_m,
  NULLIF(NULLIF(NULLIF(r.mediana_pobtot, ''), 'MI'), 'NA')::numeric AS mediana_pobtot,
  NULLIF(NULLIF(NULLIF(r.mediana_f, ''), 'MI'), 'NA')::numeric AS mediana_f,
  NULLIF(NULLIF(NULLIF(r.mediana_m, ''), 'MI'), 'NA')::numeric AS mediana_m,
  NULLIF(NULLIF(NULLIF(r.indice_env, ''), 'MI'), 'NA')::numeric AS indice_env,
  NULLIF(NULLIF(NULLIF(r.indice_env_f, ''), 'MI'), 'NA')::numeric AS indice_env_f,
  NULLIF(NULLIF(NULLIF(r.indice_env_m, ''), 'MI'), 'NA')::numeric AS indice_env_m,
  NULLIF(NULLIF(NULLIF(r.razon_dep_tot, ''), 'MI'), 'NA')::numeric AS razon_dep_tot,
  NULLIF(NULLIF(NULLIF(r.razon_dep_inf, ''), 'MI'), 'NA')::numeric AS razon_dep_inf,
  NULLIF(NULLIF(NULLIF(r.razon_dep_vej, ''), 'MI'), 'NA')::numeric AS razon_dep_vej,
  NULLIF(NULLIF(NULLIF(r.prom_hnv, ''), 'MI'), 'NA')::numeric AS prom_hnv,
  NULLIF(NULLIF(NULLIF(r.tgf, ''), 'MI'), 'NA')::numeric AS tgf,
  NULLIF(NULLIF(NULLIF(r.pcn_hf, ''), 'MI'), 'NA')::numeric AS pcn_hf,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacent, ''), 'MI'), 'NA')::numeric AS pcn_pnacent,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacent_f, ''), 'MI'), 'NA')::numeric AS pcn_pnacent_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacent_m, ''), 'MI'), 'NA')::numeric AS pcn_pnacent_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacoe, ''), 'MI'), 'NA')::numeric AS pcn_pnacoe,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacoe_f, ''), 'MI'), 'NA')::numeric AS pcn_pnacoe_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacoe_m, ''), 'MI'), 'NA')::numeric AS pcn_pnacoe_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop, ''), 'MI'), 'NA')::numeric AS pcn_pnacop,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_f, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_m, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_m,
  NULLIF(NULLIF(NULLIF(r.pnacop, ''), 'MI'), 'NA')::numeric AS pnacop,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_nac, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_nac,
  NULLIF(NULLIF(NULLIF(r.pcn_pnacop_nonac, ''), 'MI'), 'NA')::numeric AS pcn_pnacop_nonac,
  NULLIF(NULLIF(NULLIF(r.pcn_presm20, ''), 'MI'), 'NA')::numeric AS pcn_presm20,
  NULLIF(NULLIF(NULLIF(r.pcn_presom20, ''), 'MI'), 'NA')::numeric AS pcn_presom20,
  NULLIF(NULLIF(NULLIF(r.pcn_prese20, ''), 'MI'), 'NA')::numeric AS pcn_prese20,
  NULLIF(NULLIF(NULLIF(r.pcn_presoe20, ''), 'MI'), 'NA')::numeric AS pcn_presoe20,
  NULLIF(NULLIF(NULLIF(r.pcn_preseua20, ''), 'MI'), 'NA')::numeric AS pcn_preseua20,
  NULLIF(NULLIF(NULLIF(r.pcn_presop20, ''), 'MI'), 'NA')::numeric AS pcn_presop20,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_ind, ''), 'MI'), 'NA')::numeric AS pcn_pob_ind,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_ind_f, ''), 'MI'), 'NA')::numeric AS pcn_pob_ind_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_ind_m, ''), 'MI'), 'NA')::numeric AS pcn_pob_ind_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_hli, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_hli,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_hli_f, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_hli_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_hli_m, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_hli_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hlinhe, ''), 'MI'), 'NA')::numeric AS pcn_p3hlinhe,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hlinhe_f, ''), 'MI'), 'NA')::numeric AS pcn_p3hlinhe_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hlinhe_m, ''), 'MI'), 'NA')::numeric AS pcn_p3hlinhe_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hli_he, ''), 'MI'), 'NA')::numeric AS pcn_p3hli_he,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hli_he_f, ''), 'MI'), 'NA')::numeric AS pcn_p3hli_he_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p3hli_he_m, ''), 'MI'), 'NA')::numeric AS pcn_p3hli_he_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p3nhli_cli, ''), 'MI'), 'NA')::numeric AS pcn_p3nhli_cli,
  NULLIF(NULLIF(NULLIF(r.hog_ind, ''), 'MI'), 'NA')::numeric AS hog_ind,
  NULLIF(NULLIF(NULLIF(r.phog_ind, ''), 'MI'), 'NA')::numeric AS phog_ind,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_afro, ''), 'MI'), 'NA')::numeric AS pcn_pob_afro,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_afro_f, ''), 'MI'), 'NA')::numeric AS pcn_pob_afro_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pob_afro_m, ''), 'MI'), 'NA')::numeric AS pcn_pob_afro_m,
  NULLIF(NULLIF(NULLIF(r.hog_afro, ''), 'MI'), 'NA')::numeric AS hog_afro,
  NULLIF(NULLIF(NULLIF(r.phog_afro, ''), 'MI'), 'NA')::numeric AS phog_afro,
  NULLIF(NULLIF(NULLIF(r.pcon_disc, ''), 'MI'), 'NA')::numeric AS pcon_disc,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc_f, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc_m, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc0a14, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc0a14,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc15a29, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc15a29,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc30a59, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc30a59,
  NULLIF(NULLIF(NULLIF(r.pcn_pcon_disc60ym, ''), 'MI'), 'NA')::numeric AS pcn_pcon_disc60ym,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_vis, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_vis,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_aud, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_aud,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_mot, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_mot,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_men, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_men,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_mot2, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_mot2,
  NULLIF(NULLIF(NULLIF(r.pcn_pcdisc_leng, ''), 'MI'), 'NA')::numeric AS pcn_pcdisc_leng,
  NULLIF(NULLIF(NULLIF(r.pcon_limi, ''), 'MI'), 'NA')::numeric AS pcon_limi,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_vis, ''), 'MI'), 'NA')::numeric AS pcn_pclim_vis,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_oaud, ''), 'MI'), 'NA')::numeric AS pcn_pclim_oaud,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_csb, ''), 'MI'), 'NA')::numeric AS pcn_pclim_csb,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_re_co, ''), 'MI'), 'NA')::numeric AS pcn_pclim_re_co,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_mot2, ''), 'MI'), 'NA')::numeric AS pcn_pclim_mot2,
  NULLIF(NULLIF(NULLIF(r.pcn_pclim_haco, ''), 'MI'), 'NA')::numeric AS pcn_pclim_haco,
  NULLIF(NULLIF(NULLIF(r.pclim_pmen, ''), 'MI'), 'NA')::numeric AS pclim_pmen,
  NULLIF(NULLIF(NULLIF(r.psind_lim, ''), 'MI'), 'NA')::numeric AS psind_lim,
  NULLIF(NULLIF(NULLIF(r.pcn_p3ym_asis, ''), 'MI'), 'NA')::numeric AS pcn_p3ym_asis,
  NULLIF(NULLIF(NULLIF(r.pcn_p6a14_noa, ''), 'MI'), 'NA')::numeric AS pcn_p6a14_noa,
  NULLIF(NULLIF(NULLIF(r.pcn_p6a14_noa_f, ''), 'MI'), 'NA')::numeric AS pcn_p6a14_noa_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p6a14_noa_m, ''), 'MI'), 'NA')::numeric AS pcn_p6a14_noa_m,
  NULLIF(NULLIF(NULLIF(r.pnc_p6a14an, ''), 'MI'), 'NA')::numeric AS pnc_p6a14an,
  NULLIF(NULLIF(NULLIF(r.pnc_p6a14an_f, ''), 'MI'), 'NA')::numeric AS pnc_p6a14an_f,
  NULLIF(NULLIF(NULLIF(r.pnc_p6a14an_m, ''), 'MI'), 'NA')::numeric AS pnc_p6a14an_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_an, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_an,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_an_f, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_an_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_an_m, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_an_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_se, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_se,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_eb, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_eb,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_ems, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_ems,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_es, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_es,
  NULLIF(NULLIF(NULLIF(r.pcn_p15ym_pos, ''), 'MI'), 'NA')::numeric AS pcn_p15ym_pos,
  NULLIF(NULLIF(NULLIF(r.graproes, ''), 'MI'), 'NA')::numeric AS graproes,
  NULLIF(NULLIF(NULLIF(r.graproes_f, ''), 'MI'), 'NA')::numeric AS graproes_f,
  NULLIF(NULLIF(NULLIF(r.graproes_m, ''), 'MI'), 'NA')::numeric AS graproes_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pea, ''), 'MI'), 'NA')::numeric AS pcn_pea,
  NULLIF(NULLIF(NULLIF(r.pcn_pea_f, ''), 'MI'), 'NA')::numeric AS pcn_pea_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pea_m, ''), 'MI'), 'NA')::numeric AS pcn_pea_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pe_inac, ''), 'MI'), 'NA')::numeric AS pcn_pe_inac,
  NULLIF(NULLIF(NULLIF(r.pcn_pe_inac_f, ''), 'MI'), 'NA')::numeric AS pcn_pe_inac_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pe_inac_m, ''), 'MI'), 'NA')::numeric AS pcn_pe_inac_m,
  NULLIF(NULLIF(NULLIF(r.pocupada, ''), 'MI'), 'NA')::numeric AS pocupada,
  NULLIF(NULLIF(NULLIF(r.pcn_pocupada, ''), 'MI'), 'NA')::numeric AS pcn_pocupada,
  NULLIF(NULLIF(NULLIF(r.pcn_pocupada_f, ''), 'MI'), 'NA')::numeric AS pcn_pocupada_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pocupada_m, ''), 'MI'), 'NA')::numeric AS pcn_pocupada_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pdesocup, ''), 'MI'), 'NA')::numeric AS pcn_pdesocup,
  NULLIF(NULLIF(NULLIF(r.pcn_pdesocup_f, ''), 'MI'), 'NA')::numeric AS pcn_pdesocup_f,
  NULLIF(NULLIF(NULLIF(r.pcn_pdesocup_m, ''), 'MI'), 'NA')::numeric AS pcn_pdesocup_m,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_asa, ''), 'MI'), 'NA')::numeric AS pcn_pocup_asa,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_emp, ''), 'MI'), 'NA')::numeric AS pcn_pocup_emp,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_cpro, ''), 'MI'), 'NA')::numeric AS pcn_pocup_cpro,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_spag, ''), 'MI'), 'NA')::numeric AS pcn_pocup_spag,
  NULLIF(NULLIF(NULLIF(r.pder_ss, ''), 'MI'), 'NA')::numeric AS pder_ss,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_ss, ''), 'MI'), 'NA')::numeric AS pcn_pder_ss,
  NULLIF(NULLIF(NULLIF(r.pcn_psinder, ''), 'MI'), 'NA')::numeric AS pcn_psinder,
  NULLIF(NULLIF(NULLIF(r.pcn_pcssyrecac, ''), 'MI'), 'NA')::numeric AS pcn_pcssyrecac,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_imss, ''), 'MI'), 'NA')::numeric AS pcn_pder_imss,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_iste, ''), 'MI'), 'NA')::numeric AS pcn_pder_iste,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_pdom, ''), 'MI'), 'NA')::numeric AS pcn_pafil_pdom,
  NULLIF(NULLIF(NULLIF(r.pcn_pder_imssb, ''), 'MI'), 'NA')::numeric AS pcn_pder_imssb,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_ipub, ''), 'MI'), 'NA')::numeric AS pcn_pafil_ipub,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_ipriv, ''), 'MI'), 'NA')::numeric AS pcn_pafil_ipriv,
  NULLIF(NULLIF(NULLIF(r.pcn_pafil_otrai, ''), 'MI'), 'NA')::numeric AS pcn_pafil_otrai,
  NULLIF(NULLIF(NULLIF(r.pusu_ss, ''), 'MI'), 'NA')::numeric AS pusu_ss,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_imss, ''), 'MI'), 'NA')::numeric AS pcn_pusu_imss,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_iste, ''), 'MI'), 'NA')::numeric AS pcn_pusu_iste,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_pdom, ''), 'MI'), 'NA')::numeric AS pcn_pusu_pdom,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_imssb, ''), 'MI'), 'NA')::numeric AS pcn_pusu_imssb,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_ipub, ''), 'MI'), 'NA')::numeric AS pcn_pusu_ipub,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_ipriv, ''), 'MI'), 'NA')::numeric AS pcn_pusu_ipriv,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_cfarm, ''), 'MI'), 'NA')::numeric AS pcn_pusu_cfarm,
  NULLIF(NULLIF(NULLIF(r.pcn_pusu_otrai, ''), 'MI'), 'NA')::numeric AS pcn_pusu_otrai,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_ent, ''), 'MI'), 'NA')::numeric AS pcn_pasis_ent,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_oent, ''), 'MI'), 'NA')::numeric AS pcn_pasis_oent,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_15min, ''), 'MI'), 'NA')::numeric AS pcn_pasis_15min,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_30min, ''), 'MI'), 'NA')::numeric AS pcn_pasis_30min,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_1hor, ''), 'MI'), 'NA')::numeric AS pcn_pasis_1hor,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_1hym, ''), 'MI'), 'NA')::numeric AS pcn_pasis_1hym,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_cam, ''), 'MI'), 'NA')::numeric AS pcn_pasis_cam,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_bici, ''), 'MI'), 'NA')::numeric AS pcn_pasis_bici,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_met, ''), 'MI'), 'NA')::numeric AS pcn_pasis_met,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_trol, ''), 'MI'), 'NA')::numeric AS pcn_pasis_trol,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_tesc, ''), 'MI'), 'NA')::numeric AS pcn_pasis_tesc,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_taxi, ''), 'MI'), 'NA')::numeric AS pcn_pasis_taxi,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_moto, ''), 'MI'), 'NA')::numeric AS pcn_pasis_moto,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_auto, ''), 'MI'), 'NA')::numeric AS pcn_pasis_auto,
  NULLIF(NULLIF(NULLIF(r.pcn_pasis_omed, ''), 'MI'), 'NA')::numeric AS pcn_pasis_omed,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_ent, ''), 'MI'), 'NA')::numeric AS pcn_pocup_ent,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_oent, ''), 'MI'), 'NA')::numeric AS pcn_pocup_oent,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_15min, ''), 'MI'), 'NA')::numeric AS pcn_pocup_15min,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_30min, ''), 'MI'), 'NA')::numeric AS pcn_pocup_30min,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_1hor, ''), 'MI'), 'NA')::numeric AS pcn_pocup_1hor,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_2hor, ''), 'MI'), 'NA')::numeric AS pcn_pocup_2hor,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_2hym, ''), 'MI'), 'NA')::numeric AS pcn_pocup_2hym,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_cam, ''), 'MI'), 'NA')::numeric AS pcn_pocup_cam,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_bici, ''), 'MI'), 'NA')::numeric AS pcn_pocup_bici,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_met, ''), 'MI'), 'NA')::numeric AS pcn_pocup_met,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_trol, ''), 'MI'), 'NA')::numeric AS pcn_pocup_trol,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_tper, ''), 'MI'), 'NA')::numeric AS pcn_pocup_tper,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_taxi, ''), 'MI'), 'NA')::numeric AS pcn_pocup_taxi,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_moto, ''), 'MI'), 'NA')::numeric AS pcn_pocup_moto,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_auto, ''), 'MI'), 'NA')::numeric AS pcn_pocup_auto,
  NULLIF(NULLIF(NULLIF(r.pcn_pocup_omed, ''), 'MI'), 'NA')::numeric AS pcn_pocup_omed,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_solt, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_solt,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_solt_f, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_solt_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_solt_m, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_solt_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_cul, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_cul,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_cul_f, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_cul_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_cul_m, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_cul_m,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_sepa, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_sepa,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_sepa_f, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_sepa_f,
  NULLIF(NULLIF(NULLIF(r.pcn_p12ym_sepa_m, ''), 'MI'), 'NA')::numeric AS pcn_p12ym_sepa_m,
  NULLIF(NULLIF(NULLIF(r.tothog, ''), 'MI'), 'NA')::numeric AS tothog,
  NULLIF(NULLIF(NULLIF(r.hogjef_f, ''), 'MI'), 'NA')::numeric AS hogjef_f,
  NULLIF(NULLIF(NULLIF(r.hogjef_m, ''), 'MI'), 'NA')::numeric AS hogjef_m,
  NULLIF(NULLIF(NULLIF(r.pobhog, ''), 'MI'), 'NA')::numeric AS pobhog,
  NULLIF(NULLIF(NULLIF(r.phogjef_f, ''), 'MI'), 'NA')::numeric AS phogjef_f,
  NULLIF(NULLIF(NULLIF(r.phogjef_m, ''), 'MI'), 'NA')::numeric AS phogjef_m,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_fam, ''), 'MI'), 'NA')::numeric AS pcn_hog_fam,
  NULLIF(NULLIF(NULLIF(r.pcn_pobhog_fam, ''), 'MI'), 'NA')::numeric AS pcn_pobhog_fam,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_nfam, ''), 'MI'), 'NA')::numeric AS pcn_hog_nfam,
  NULLIF(NULLIF(NULLIF(r.pcn_pobhog_nfam, ''), 'MI'), 'NA')::numeric AS pcn_pobhog_nfam,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_perc, ''), 'MI'), 'NA')::numeric AS pcn_hog_perc,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_nperc, ''), 'MI'), 'NA')::numeric AS pcn_hog_nperc,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_gob, ''), 'MI'), 'NA')::numeric AS pcn_hog_gob,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_jub, ''), 'MI'), 'NA')::numeric AS pcn_hog_jub,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_oviv, ''), 'MI'), 'NA')::numeric AS pcn_hog_oviv,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_opais, ''), 'MI'), 'NA')::numeric AS pcn_hog_opais,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_alim_n, ''), 'MI'), 'NA')::numeric AS pcn_hog_alim_n,
  NULLIF(NULLIF(NULLIF(r.pcn_hog_alim, ''), 'MI'), 'NA')::numeric AS pcn_hog_alim,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_adl1, ''), 'MI'), 'NA')::numeric AS pcn_alim_adl1,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_adl2, ''), 'MI'), 'NA')::numeric AS pcn_alim_adl2,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_adl3, ''), 'MI'), 'NA')::numeric AS pcn_alim_adl3,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_adl1, ''), 'MI'), 'NA')::numeric AS pcn_ing_adl1,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_adl2, ''), 'MI'), 'NA')::numeric AS pcn_ing_adl2,
  NULLIF(NULLIF(NULLIF(r.hog_men_alim, ''), 'MI'), 'NA')::numeric AS hog_men_alim,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_men1, ''), 'MI'), 'NA')::numeric AS pcn_alim_men1,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_men2, ''), 'MI'), 'NA')::numeric AS pcn_alim_men2,
  NULLIF(NULLIF(NULLIF(r.pcn_alim_men3, ''), 'MI'), 'NA')::numeric AS pcn_alim_men3,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_men1, ''), 'MI'), 'NA')::numeric AS pcn_ing_men1,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_men2, ''), 'MI'), 'NA')::numeric AS pcn_ing_men2,
  NULLIF(NULLIF(NULLIF(r.pcn_ing_men3, ''), 'MI'), 'NA')::numeric AS pcn_ing_men3,
  NULLIF(NULLIF(NULLIF(r.pcn_desp_inseg, ''), 'MI'), 'NA')::numeric AS pcn_desp_inseg,
  NULLIF(NULLIF(NULLIF(r.pcn_desp_catas, ''), 'MI'), 'NA')::numeric AS pcn_desp_catas,
  NULLIF(NULLIF(NULLIF(r.vivparhab, ''), 'MI'), 'NA')::numeric AS vivparhab,
  NULLIF(NULLIF(NULLIF(r.vivparhab_c, ''), 'MI'), 'NA')::numeric AS vivparhab_c,
  NULLIF(NULLIF(NULLIF(r.ocupvivpar, ''), 'MI'), 'NA')::numeric AS ocupvivpar,
  NULLIF(NULLIF(NULLIF(r.prom_ocup, ''), 'MI'), 'NA')::numeric AS prom_ocup,
  NULLIF(NULLIF(NULLIF(r.pro_ocup_c, ''), 'MI'), 'NA')::numeric AS pro_ocup_c,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_2_5ocu, ''), 'MI'), 'NA')::numeric AS pcn_vph_2_5ocu,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pdesh, ''), 'MI'), 'NA')::numeric AS pcn_vph_pdesh,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pasb, ''), 'MI'), 'NA')::numeric AS pcn_vph_pasb,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pmad, ''), 'MI'), 'NA')::numeric AS pcn_vph_pmad,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_ptab, ''), 'MI'), 'NA')::numeric AS pcn_vph_ptab,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tdesh, ''), 'MI'), 'NA')::numeric AS pcn_vph_tdesh,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tasb, ''), 'MI'), 'NA')::numeric AS pcn_vph_tasb,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tlosa, ''), 'MI'), 'NA')::numeric AS pcn_vph_tlosa,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_totro, ''), 'MI'), 'NA')::numeric AS pcn_vph_totro,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pisoti, ''), 'MI'), 'NA')::numeric AS pcn_vph_pisoti,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pisocem, ''), 'MI'), 'NA')::numeric AS pcn_vph_pisocem,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pisomad, ''), 'MI'), 'NA')::numeric AS pcn_vph_pisomad,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_1cuart, ''), 'MI'), 'NA')::numeric AS pcn_vph_1cuart,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_2cuart, ''), 'MI'), 'NA')::numeric AS pcn_vph_2cuart,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_3ymasc, ''), 'MI'), 'NA')::numeric AS pcn_vph_3ymasc,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_1dor, ''), 'MI'), 'NA')::numeric AS pcn_vph_1dor,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_2ymasd, ''), 'MI'), 'NA')::numeric AS pcn_vph_2ymasd,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cint, ''), 'MI'), 'NA')::numeric AS pcn_vph_cint,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_csep, ''), 'MI'), 'NA')::numeric AS pcn_vph_csep,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cotro, ''), 'MI'), 'NA')::numeric AS pcn_vph_cotro,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_comgas, ''), 'MI'), 'NA')::numeric AS pcn_vph_comgas,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_comele, ''), 'MI'), 'NA')::numeric AS pcn_vph_comele,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_c_elec, ''), 'MI'), 'NA')::numeric AS pcn_vph_c_elec,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_aguadv, ''), 'MI'), 'NA')::numeric AS pcn_vph_aguadv,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_drenaj, ''), 'MI'), 'NA')::numeric AS pcn_vph_drenaj,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_c_serv, ''), 'MI'), 'NA')::numeric AS pcn_vph_c_serv,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_excsa, ''), 'MI'), 'NA')::numeric AS pcn_vph_excsa,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_dsadma, ''), 'MI'), 'NA')::numeric AS pcn_vph_dsadma,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tinaco, ''), 'MI'), 'NA')::numeric AS pcn_vph_tinaco,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cister, ''), 'MI'), 'NA')::numeric AS pcn_vph_cister,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_bomba, ''), 'MI'), 'NA')::numeric AS pcn_vph_bomba,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_rega, ''), 'MI'), 'NA')::numeric AS pcn_vph_rega,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_boiler, ''), 'MI'), 'NA')::numeric AS pcn_vph_boiler,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_solar, ''), 'MI'), 'NA')::numeric AS pcn_vph_solar,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_aire, ''), 'MI'), 'NA')::numeric AS pcn_vph_aire,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_panel, ''), 'MI'), 'NA')::numeric AS pcn_vph_panel,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_organi, ''), 'MI'), 'NA')::numeric AS pcn_vph_organi,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_animal, ''), 'MI'), 'NA')::numeric AS pcn_vph_animal,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_planta, ''), 'MI'), 'NA')::numeric AS pcn_vph_planta,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_vender, ''), 'MI'), 'NA')::numeric AS pcn_vph_vender,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cambasu, ''), 'MI'), 'NA')::numeric AS pcn_vph_cambasu,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cntbasu, ''), 'MI'), 'NA')::numeric AS pcn_vph_cntbasu,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_elimbas, ''), 'MI'), 'NA')::numeric AS pcn_vph_elimbas,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_refri, ''), 'MI'), 'NA')::numeric AS pcn_vph_refri,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_lavad, ''), 'MI'), 'NA')::numeric AS pcn_vph_lavad,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_hmicro, ''), 'MI'), 'NA')::numeric AS pcn_vph_hmicro,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_autom, ''), 'MI'), 'NA')::numeric AS pcn_vph_autom,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_moto, ''), 'MI'), 'NA')::numeric AS pcn_vph_moto,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_bici, ''), 'MI'), 'NA')::numeric AS pcn_vph_bici,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_radio, ''), 'MI'), 'NA')::numeric AS pcn_vph_radio,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tv, ''), 'MI'), 'NA')::numeric AS pcn_vph_tv,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pc, ''), 'MI'), 'NA')::numeric AS pcn_vph_pc,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_telef, ''), 'MI'), 'NA')::numeric AS pcn_vph_telef,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_cel, ''), 'MI'), 'NA')::numeric AS pcn_vph_cel,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_inter, ''), 'MI'), 'NA')::numeric AS pcn_vph_inter,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_tvp, ''), 'MI'), 'NA')::numeric AS pcn_vph_tvp,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_propia, ''), 'MI'), 'NA')::numeric AS pcn_vph_propia,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_alqui, ''), 'MI'), 'NA')::numeric AS pcn_vph_alqui,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_prest, ''), 'MI'), 'NA')::numeric AS pcn_vph_prest,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_otrasit, ''), 'MI'), 'NA')::numeric AS pcn_vph_otrasit,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_propresi, ''), 'MI'), 'NA')::numeric AS pcn_vph_propresi,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_pernores, ''), 'MI'), 'NA')::numeric AS pcn_vph_pernores,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_noescri, ''), 'MI'), 'NA')::numeric AS pcn_vph_noescri,
  NULLIF(NULLIF(NULLIF(r.pcn_vph_escrides, ''), 'MI'), 'NA')::numeric AS pcn_vph_escrides
FROM eic_2025_municipio_raw r
WHERE r.estimador IN ('Error estándar', 'Límite inferior de confianza',
                      'Límite superior de confianza', 'Coeficiente de variación')
  AND r.cve_loc = '0000'
  AND r.mun NOT IN ('000', '997');

-- eic_2025_municipio_censo_parity: absolutes named like the Censo 2020
-- municipal columns the API reads. Direct counts are EIC absolutes; derived
-- ones are PCN_X x base / 100, rounded, with the base INEGI publishes for each
-- percentage (brief §3): VIVPARHAB_C for vph_*, PDER_SS for the institution
-- shares, P_12YMAS for pea / p12ym_*, P_15YMAS for p15ym_*, P_3YMAS for
-- p3ym_hli, indigenous-language speakers (unrounded) for p3hlinhe / p3hli_he,
-- P_5YMAS for the 2020 residence columns (named pres2020 / presoe20: EIC asks
-- about October 2020, not 2015), POBTOT otherwise. tvivhab = VIVPARHAB
-- (private inhabited dwellings only); pder_segp approximates with
-- PCN_PAFIL_IPUB. No equivalent in EIC: p_18ymas, tvivpar, religion,
-- p15pri_* / p15sec_*, p18ym_pb, vph_spmvpi / vph_cvj / vph_snbien.
CREATE OR REPLACE VIEW eic_2025_municipio_censo_parity AS
SELECT
  e.cve_mun,
  e.cve_ent AS entidad,
  e.mun,
  e.nom_ent,
  e.nom_mun,
  e.enumeracion_completa,
  e.muestra_insuficiente,
  round(e.pobtot)::bigint AS pobtot,
  round(e.pobfem)::bigint AS pobfem,
  round(e.pobmas)::bigint AS pobmas,
  round(e.p_12ymas)::bigint AS p_12ymas,
  round(e.p_15ymas)::bigint AS p_15ymas,
  round((e.pcn_p_60a64 + e.pcn_p_65a69 + e.pcn_p_70a74 + e.pcn_p_75ymas) * e.pobtot / 100)::bigint AS p_60ymas,
  round(e.pcn_pea * e.p_12ymas / 100)::bigint AS pea,
  round(e.pocupada)::bigint AS pocupada,
  e.graproes AS graproes,
  round(e.vivparhab)::bigint AS tvivhab,
  round(e.pcn_p3ym_hli * e.p_3ymas / 100)::bigint AS p3ym_hli,
  round(e.pcn_p3hlinhe * (e.pcn_p3ym_hli * e.p_3ymas / 100) / 100)::bigint AS p3hlinhe,
  round(e.pcn_p3hli_he * (e.pcn_p3ym_hli * e.p_3ymas / 100) / 100)::bigint AS p3hli_he,
  round(e.phog_ind)::bigint AS phog_ind,
  round(e.pcn_pob_afro * e.pobtot / 100)::bigint AS pob_afro,
  round(e.pcn_pnacent * e.pobtot / 100)::bigint AS pnacent,
  round(e.pcn_pnacoe * e.pobtot / 100)::bigint AS pnacoe,
  round(e.pcn_prese20 * e.p_5ymas / 100)::bigint AS pres2020,
  round(e.pcn_presoe20 * e.p_5ymas / 100)::bigint AS presoe20,
  round(e.pcn_p15ym_an * e.p_15ymas / 100)::bigint AS p15ym_an,
  round(e.pcn_p15ym_se * e.p_15ymas / 100)::bigint AS p15ym_se,
  round(e.pcn_p12ym_solt * e.p_12ymas / 100)::bigint AS p12ym_solt,
  round(e.pcn_p12ym_cul * e.p_12ymas / 100)::bigint AS p12ym_casa,
  round(e.pcn_p12ym_sepa * e.p_12ymas / 100)::bigint AS p12ym_sepa,
  round(e.pcon_disc)::bigint AS pcon_disc,
  round(e.pcon_limi)::bigint AS pcon_limi,
  round(e.psind_lim)::bigint AS psind_lim,
  round(e.pcn_psinder * e.pobtot / 100)::bigint AS psinder,
  round(e.pder_ss)::bigint AS pder_ss,
  round(e.pcn_pder_imss * e.pder_ss / 100)::bigint AS pder_imss,
  round(e.pcn_pder_iste * e.pder_ss / 100)::bigint AS pder_iste,
  round(e.pcn_pder_imssb * e.pder_ss / 100)::bigint AS pder_imssb,
  round(e.pcn_pafil_ipriv * e.pder_ss / 100)::bigint AS pafil_ipriv,
  round(e.pcn_pafil_ipub * e.pder_ss / 100)::bigint AS pder_segp,
  round(e.pcn_vph_inter * e.vivparhab_c / 100)::bigint AS vph_inter,
  round(e.pcn_vph_autom * e.vivparhab_c / 100)::bigint AS vph_autom,
  round(e.pcn_vph_refri * e.vivparhab_c / 100)::bigint AS vph_refri,
  round(e.pcn_vph_lavad * e.vivparhab_c / 100)::bigint AS vph_lavad,
  round(e.pcn_vph_hmicro * e.vivparhab_c / 100)::bigint AS vph_hmicro,
  round(e.pcn_vph_moto * e.vivparhab_c / 100)::bigint AS vph_moto,
  round(e.pcn_vph_bici * e.vivparhab_c / 100)::bigint AS vph_bici,
  round(e.pcn_vph_radio * e.vivparhab_c / 100)::bigint AS vph_radio,
  round(e.pcn_vph_tv * e.vivparhab_c / 100)::bigint AS vph_tv,
  round(e.pcn_vph_pc * e.vivparhab_c / 100)::bigint AS vph_pc,
  round(e.pcn_vph_telef * e.vivparhab_c / 100)::bigint AS vph_telef,
  round(e.pcn_vph_cel * e.vivparhab_c / 100)::bigint AS vph_cel,
  round(e.pcn_vph_tvp * e.vivparhab_c / 100)::bigint AS vph_stvp
FROM eic_2025_municipio e;
